- src/views/schema/routes/edit.vue
- src/views/schema/service/list.vue
简单试用了下 dashboard， 发现以下问题， 
1. service 如果没有 plugins 配置的话，会显示一直加载。
2. routers 可以直接绑定 upsteam, 所以应当是可以取消 upsteam_id 和 service_id  的绑定。
提交 PR 修复这两个问题，如有不对，请批正。
> 修复 service 没有 plugins 属性不能加载和可以取消设置 upsteam 和 service.

- LICENSE
- NOTICE
fixed https://github.com/apache/incubator-apisix-dashboard/issues/54
> license: moved  License information to LICENSE.

- src/components/VarArgs/index.vue
- src/lang/en.ts
- src/lang/zh.ts
- src/views/schema/routes/edit.vue
- src/views/schema/upstream/edit.vue
- vue.config.js
feature: https://github.com/apache/incubator-apisix-dashboard/issues/161
> feature:allow set vars filter in router configuration page

- src/components/PluginDialog/index.vue
- src/lang/en.ts
- src/lang/zh.ts
add feature #166 
Make array properties available for graphical editing
Add translation content
> feature: add array property editor

- src/components/PluginDialog/index.vue
The PR has fixed a bug that if close the plugin dialog not by the cancel button, we can never open a new one.
> fix a  plugin dialog can't reopen bug

- api/conf/conf.go
- api/conf/mysql.go
- api/filter/logging.go
- api/filter/recover.go
- api/filter/request_id.go
- api/log/log.go
- api/main.go
- api/route/consumer.go
- api/route/healthz.go
- api/route/plugin.go
- api/route/route.go
- api/route/ssl.go
- api/route/upstream.go
- api/service/base.go
- api/service/consumer.go
- api/service/consumer_test.go
- api/service/plugin.go
- api/service/route.go
- api/service/route_test.go
- api/service/ssl.go
- api/service/ssl_test.go
- api/service/upstream.go
- api/utils/http.go
Use `gofmt` command to format codes, as well as re-organize the imports in a conventional way via `goimports` command. 
> BTW: I guess that would be great if we add these two command to make static check for go codes. Maybe that could be done in another PR.
> Fix incorrect format of some go source files

- api/errno/error.go
- api/script/db/schema.sql
- api/service/consumer.go
- api/service/ssl.go
- api/service/ssl_test.go
1. add transaction for ssl and consumer
2. define status for respond Message
3. checking sni exists in ssl certs
> feat: add transaction for ssl and consumer

- src/locales/zh-CN.ts
- src/pages/Metrics/Metrics.tsx
- src/pages/Metrics/index.ts
- src/pages/Metrics/locales/en-US.ts
- src/pages/Metrics/locales/zh-CN.ts
> feat(i18n): metrics module

- src/access.ts
- src/components/PluginForm/locales/en-US.ts
- src/components/PluginForm/locales/zh-CN.ts
- src/components/PluginPage/PluginPage.tsx
- src/pages/Consumer/Create.tsx
- src/pages/Consumer/List.tsx
- src/pages/Route/List.tsx
- src/pages/Route/transform.ts
- src/pages/SSL/Create.tsx
- src/pages/SSL/service.ts
- src/pages/Upstream/Create.tsx
- src/pages/Upstream/List.tsx
This PR involves:
- Disable some checks in certain files by adding comments at the beginning of files
- Some format improvement
Resolves https://github.com/apache/apisix-dashboard/issues/340
@juzhiyuan Kindly review
> fix(ci): resolve lint failures

- api/Dockerfile
Fixes #361 .
This PR is going to use ash, which is the default shell environment in alpine v3.11, to execute the `build.sh`.
> fix(deploy): failed to start manager_api

- I18N_USER_GUIDE.md
___
- Description
- How to fix?
___
A clearer description about i18n refer to the Proposal in https://github.com/apache/apisix-dashboard/issues/331
> docs: create I18N_USER_GUIDE.md

- .github/workflows/deploy.yml
- README.md
- compose/README.md
- config/proxy.ts
- netlify.toml
- src/app.tsx
- src/constants.ts
- src/helpers.tsx
- src/locales/en-US/setting.ts
- src/locales/zh-CN/setting.ts
- src/pages/Setting/Setting.tsx
- src/pages/Setting/locales/en-US.ts
- src/pages/Setting/locales/zh-CN.ts
- src/pages/Setting/typingd.d.ts
- src/services/user.ts
> feat(Doc): added deploy doc for docker

- src/pages/Route/components/Step1/MatchingRulesView.tsx
- src/pages/Route/components/Step2/HttpHeaderRewriteView.tsx
- src/pages/Route/components/Step2/RequestRewriteView.tsx
- src/pages/Route/constants.ts
- src/pages/Route/locales/en-US.ts
- src/pages/Route/locales/zh-CN.ts
- src/pages/Route/transform.ts
- src/pages/Route/typing.d.ts
#375 
___
- Description
- How to fix?
___
I tried to realize the feature in this pr，and the UE is as follows:
1. rename the upstreamPath radio items ,and add a new item
2. when I choose `static` radio Item,
3. when I choose 'regx' radio item,
and the postData key: upstream_path
Interface test passed.
> feat(route): route add params mapping feature

- README.md
- README.zh-CN.md
#380 
___
- Description
- How to fix?
___
Add file README.zh-CN.md
> README in Chinese

- compose/dashboard_conf/nginx.conf
#396 
___
- Description
- How to fix?
1. according to https://gist.github.com/zxhfighter/7560812  add `error_page  405  =200 $uri;`
1. in dashboard docker container, there is no hosts config about 'manage', so change
```
location /apisix/admin {
proxy_pass http://manage:8080/apisix/admin;
}
```
to
```
location /apisix/admin {
proxy_pass http://192.17.5.15:8080/apisix/admin;
}
```
___
> fix: dashboard /user/login get error code 405

- compose/apisix_conf/config.yaml
___
- Description
- How to fix?
fix typo
___
> fix: APISIX using default admin key in docker compose

- .github/apisix-config.yaml
- .github/workflows/api_ci.yml
- .github/workflows/api_cicd.yml
- api/Dockerfile
- api/build.sh
- api/conf/conf.go
- api/route/route.go
- api/script/db/schema.sql
- api/service/route.go
- api/service/route_test.go
- compose/manager_conf/build.sh
- licenses/LICENSE-dag-to-lua.txt
___
feat: support generate `script` for APISIX
> feat: support generate `script` for APISIX

- .actions/ASF-Release.cfg
- .github/workflows/api_ci.yml
- .github/workflows/license_ci.yml
- compose/dashboard_conf/nginx.conf
- docker/nginx.conf
___
- Description
- How to fix?
___
> feature:Independent license check operation file.

- api/errno/error.go
- api/route/route.go
- api/route/route_group_test.go
- api/route/route_test.go
- api/service/route_group.go
- api/service/route_group_test.go
1. this pr could Independently resolve issue #452 
1. this pr could also resolve the ci error in pr #450 
___
- Description
- How to fix?
___
1. refer to the https://github.com/apache/apisix-dashboard/issues/431#issuecomment-684158042, user could ungroup a  route which is already in a routeGroup.
1.  routeGroup is not a required item when create/edit the route
1.  decouple api and front-end
> feat: support ungroup in manager api

- api/errno/error.go
- api/route/route.go
- api/route/route_test.go
- api/script/db/schema.sql
- api/service/route.go
issue #437 manage api
___
- Description
- How to fix?
___
1. add a Column to route, called `status`
1. `status = true`, means create a new route in both mysql and apisix;  `status=false`: means create a route only in mysql
1. modified the logic of editing and deleting route at the same time, 
1. add manager apis to support change route `status`
> feat: add publish status to route in manager api

- package.json
- src/pages/Route/Create.tsx
- src/pages/Route/components/CreateStep4/CreateStep4.tsx
- src/pages/Route/components/Step1/index.tsx
- src/pages/Route/components/Step3/index.tsx
- yarn.lock
___
- Description
- How to fix?
___
update plugin's dependency
> feat: added new plugin dependency

- package.json
- src/pages/Route/Create.tsx
- src/pages/Route/components/CreateStep4/CreateStep4.tsx
- src/pages/Route/components/Step1/MatchingRulesView.tsx
- src/pages/Route/components/Step1/MetaView.tsx
- src/pages/Route/components/Step1/RequestConfigView.tsx
- src/pages/Route/components/Step1/index.tsx
- src/pages/Route/components/Step2/HttpHeaderRewriteView.tsx
- src/pages/Route/components/Step2/RequestRewriteView.tsx
- src/pages/Route/components/Step2/index.tsx
- src/pages/Route/constants.ts
- src/pages/Route/service.ts
- src/pages/Route/transform.ts
- src/pages/Route/typing.d.ts
- yarn.lock
___
- Description
- How to fix?
___
> feat: improve route

- package.json
___
- Description
In [README/Build the dashboard](https://github.com/apache/apisix-dashboard#build-the-dashboard), only `yarn` is mentioned but `npm` is used instead of `yarn` in `package.json` multiple times. It will throw errors and cause confusion to users who have installed yarn according to README but without `npm` on their machines.
- How to fix?
`npm` is not actually used in the project. In `package.json`, it acts as a command caller. So simply dropping `npm` works.
All `npm` has been replaced to `yarn`.
> style: Drop `npm run` in package.json

- api/errno/error.go
- api/internal/core/entity/entity.go
- api/internal/core/entity/query.go
- api/internal/core/store/query.go
- api/internal/core/store/selector.go
- api/internal/core/store/selector_test.go
- api/internal/core/store/store.go
- api/internal/core/store/storehub.go
- api/internal/handler/consumer/consumer.go
- api/internal/handler/route/route.go
- api/internal/handler/service/service.go
- api/internal/handler/ssl/ssl.go
- api/internal/handler/upstream/upstream.go
- api/internal/utils/consts/api_error.go
- api/main.go
- api/route/base_test.go
- api/route/route_test.go
___
feat: refactor apis for existing check and other apis
such as:
`/apisix/admin/notexist/upstreams`
`/apisix/admin/names/upstreams`
`/apisix/admin/notexist/routes`
`/apisix/admin/check_ssl_cert`
and so on.
> feat: refactor apis for existing check and other apis

- .github/workflows/api_newci.yml
resolve #542 
Create a new GitHub Workflow to embedding static files into Go binaries.
> feat(CI): NewCI for embedding static files into Go binaries

- api/internal/handler/route/route.go
- api/internal/handler/route/route_test.go
- api/internal/handler/service/service.go
- api/internal/handler/service/service_test.go
___
fix: check whether it is nil before using a variable as an object, otherwise it will cause a 500 error.
> fix: check whether it is nil before using a variable as a object

- web/src/pages/Route/Create.tsx
- web/src/pages/Route/components/Step3/index.tsx
- web/src/pages/Route/transform.ts
resolved #688 
___
- Description
fix: enable HTTPS setting unsuccessful in Route.
- How to fix?
___
> fix: enable HTTPS setting unsuccessful in Route

- .gitignore
- api/build-tools/schema-sync.sh
fix https://github.com/apache/apisix-dashboard/issues/646
> chore: exit if any error and specify the download file name when download by `wget`

- api/internal/core/entity/format.go
- api/internal/handler/upstream/upstream_test.go
> fix: an error will occur if `pass_host` is set to `node` when creating upstream

- web/src/helpers.tsx
- web/src/pages/Consumer/List.tsx
- web/src/pages/Route/List.tsx
- web/src/pages/SSL/List.tsx
- web/src/pages/Upstream/List.tsx
resolve https://github.com/apache/apisix-dashboard/issues/734
> fix: invalid values from the manager-api

- .github/workflows/go-lint.yml
- .github/workflows/golang-lint.yml
- Makefile
- README.md
- README.zh-CN.md
- docs/deploy-with-docker.zh-CN.md
- docs/deploy.md
- docs/deploy.zh-CN.md
- docs/develop.md
- docs/develop.zh-CN.md
> docs: add makefile && modify  develop and deploy  docs

- .github/workflows/deploy-with-docker.yml
- api/build-tools/schema-sync.lua
- api/build-tools/schema-sync.sh
- docs/develop.md
- docs/develop.zh-CN.md
support specifying APISIX path to generate json schema
> feat: support specifying APISIX path to generate json schema

- api/internal/handler/consumer/consumer.go
> fix: used dashboard add consumer of jwt, would have an error when get the jwt token 

- web/src/global.less
___
- Description
When step to the third step of create/edit route: plugin Config, double scroll bars will appear on the page, which is not convenient for user .
- How to fix?
> fix: double scroll bar in plugin page

- Makefile
___
- Description
- How to fix?
___
https://stackoverflow.com/questions/53283809/yarn-install-error-failed-to-download-chromium
> feat: skip puppeteer chromium download when build

- api/main.go
- api/test/shell/cli_test.sh
resolve #737
___
- Please describe your requirements or improvement suggestions.
Hi, I do some changes to cli_test.sh
1. I think there's no need to change the log file path, so I use `echo > $logfile` to clean up the log file.
2. Create a `check_logfile` function to reduce repetitive code.
> feat: install signal handler for graceful shutdown

- api/conf/conf.go
- api/internal/core/store/store_mock.go
- api/internal/handler/consumer/consumer_test.go
- api/log/zap.go
- api/main.go
This pr is a demo about how to do a real `unit test` in handler.
I also remove the `init` in `conf` and `log`, go is recommended to use explicit initial function instead of implicit `init`
> feat: add a hanlder unit test for upstream and remove init

- api/internal/core/entity/entity.go
- api/internal/core/entity/format.go
- api/internal/core/entity/format_test.go
close #786
close #783
two issues are caused by nodes format
> fix: nodes format not works

- api/go.mod
- api/go.sum
- api/internal/handler/handler.go
- api/main.go
- api/test/e2e/route_test.go
- Add middleware to transform error, resolve #568 
- Rename `placeholder.txt` to `.gitkeep`, It is more suitable
> chore: add middleware to transform error and rename placeholder.txt

- api/internal/core/store/validate.go
- api/internal/core/store/validate_test.go
- api/internal/handler/handler.go
fix  #914
typo:  `scheme validate fail` -> `schema validate failed`
> fix: typo `scheme validate fail` should be `schema validate failed`

- api/test/e2e/base.go
- api/test/e2e/consumer_test.go
- api/test/e2e/id_compatible_test.go
- api/test/e2e/route_service_upstream_test.go
- api/test/e2e/route_test.go
- api/test/e2e/route_with_auth_plugin_test.go
- api/test/e2e/route_with_limit_plugin_test.go
- api/test/e2e/route_with_log_plugin_test.go
- api/test/e2e/route_with_methods_test.go
- api/test/e2e/route_with_metric_plugin_test.go
- api/test/e2e/route_with_plugin_orchestration_test.go
- api/test/e2e/route_with_plugin_proxy_rewrite_test.go
- api/test/e2e/route_with_trace_plugin_test.go
- api/test/e2e/route_with_uri_uris_test.go
- api/test/e2e/route_with_valid_remote_addr_test.go
- api/test/e2e/route_with_vars_test.go
- api/test/e2e/ssl_test.go
- api/test/e2e/upstream_test.go
fix typo, `MangerApiExpect` should be `ManagerApiExpect`
> chore: fix typo, `MangerApiExpect` should be `ManagerApiExpect`

- api/go.sum
- api/internal/utils/utils.go
- api/internal/utils/utils_test.go
fix #938 
___
- Description
remove network dependency for snowflake 
- How to fix?
Get IP in local
> fix: snowflake remove network dependency

- web/src/pages/Route/transform.ts
___
- Description
remote_addrs should not be [""]
close #940 
- How to fix?
___
> fix: omit remote_addrs when users don't input it

- api/internal/core/store/validate.go
- api/internal/core/store/validate_test.go
related #940 
we should not sync the json schema outside APISIX v2.1, so we need to hack to fix it.
> fix: hack to fix the checking of `remote_addrs`

- api/test/e2e/base.go
Under normal circumstances, after a short sleep, APISIX can synchronize the data from ETCD and works normally. 
But once there is network jitter, or the CPU who processing ETCD is just busy, or APISIX's watch is just timeout, the time required for synchronization will become longer. 
When the next request arrives, the data may not be synchronized to APISIX. 
So by increasing the sleep time, we could reduce the probability of failure and increase stability.
close #907
close #923
> ci: increase the sleep time to fix e2e test unstable issue

- api/test/e2e/route_service_upstream_test.go
- api/test/e2e/route_with_limit_plugin_test.go
close #998 
___
- Description
In `route_service_upstream_test.go`, r2 is used as the route ID. As a result, r1 and r2 may coexist, and the same uri is used, which may produce different results
- How to fix?
Route always use the same ID, and confirm that the uri has not been created before use
> fix: fix router name conflict in route_service_upstream_test.go

- README.md
- api/conf/schema.json
- api/test/e2e/route_with_priority_test.go
- web/src/global.tsx
- web/src/locales/en-US/component.ts
- web/src/locales/en-US/globalHeader.ts
- web/src/pages/Route/locales/en-US.ts
- web/src/pages/Route/typing.d.ts
> fix: spelling

- api/filter/authentication.go
- api/internal/core/entity/format.go
- api/internal/core/storage/etcd.go
- api/internal/core/store/store.go
- api/internal/core/store/storehub.go
- api/internal/core/store/validate.go
- api/log/zap.go
- api/main.go
- api/test/shell/cli_test.sh
1. add more error log.
2. use %s for more suitable for reading.
3. display the true caller for easier to locate problem.
close #730
> chore: enrich error log

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- api/conf/schema.json
- web/src/components/Plugin/service.ts
___
- Description
- How to fix?
___
> doc: fix typo

- web/src/components/Plugin/CodeMirrorDrawer.tsx
- web/src/components/Plugin/PluginPage.tsx
- web/src/pages/Route/components/Step1/RequestConfigView.tsx
- web/src/pages/Route/locales/en-US.ts
- web/src/pages/Route/locales/zh-CN.ts
- web/src/pages/Route/transform.ts
resolve https://github.com/apache/apisix-dashboard/issues/879
> feat(Route): added priority field

- .github/workflows/frontend-e2e-test.yml
- .github/workflows/gitleaks.yml
- CHANGELOG.md
- Makefile
- api/conf/conf.yaml
- api/test/docker-deploy/docker-compose.yaml
- api/test/docker/docker-compose.yaml
- api/test/docker/upstream.conf
- api/test/e2e/id_compatible_test.go
- api/test/e2e/route_with_trace_plugin_test.go
- api/test/e2e/upstream_test.go
- api/test/shell/docker_deploy_test.sh
- docs/deploy-with-docker.md
___
- Description
- How to fix?
___
> refactor: 🧹 remove trailing whitespace

- .github/workflows/lint.yml
- .markdownlint.yml
- CONTRIBUTING.md
- Add a Markdownlint config file
- Lint Markdown for MD038/no-space-in-code Spaces inside code span elements
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md038---spaces-inside-code-span-elements
___
- Description
- How to fix?
___
Adding an npm based Markdown linter to standardize the code.
> feat(CI): add a GitHub Action to lint the Markdown

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/gitleaks.yml
- .github/workflows/lint.yml
- .github/workflows/markdown-link-checker.yml
- .yamllint
- api/conf/conf.yaml
- api/test/docker-deploy/docker-compose.yaml
- api/test/docker/apisix_config.yaml
- api/test/docker/docker-compose.yaml
- api/test/docker/manager-api-conf.yaml
- add a `.yamllint` config file
- lint some YAML
___
- Description
- How to fix?
___
Linting the YAML will standardize the code.  Running on CI will stop regressions.
> feat(CI): add a GitHub Action to lint the YAML

- api/conf/conf.go
- api/internal/route.go
- api/test/shell/cli_test.sh
___
- Description
When I build apisix-dashboard and run :  `APISIX_API_WORKDIR=/usr/local/apisix-dashboard/ /usr/local/bin/manager-api` at /root , 
there is no erros and said : 
```
2020-12-15T17:35:09.269+0800    filter/request_id.go:41 /       {"status": 404, "host": "10.1.30.28:9000", "query": "", "requestId": "69920330-aec8-4d31-b2f6-374909b0b3ed", "latency": 0, "remoteIP": "10.1.30.99", "method": "GET", "errs": []}
2020-12-15T17:35:13.961+0800    filter/request_id.go:41 /       {"status": 404, "host": "10.1.30.28:9000", "query": "", "requestId": "164126fd-adc8-4b0a-a434-fa4bc79209ff", "latency": 0, "remoteIP": "10.1.30.99", "method": "GET", "errs": []} …
```
> fix: absolute Paths conf.WebDir

- api/internal/handler/route/route.go
- api/internal/handler/route/route_test.go
- api/internal/utils/utils.go
- api/internal/utils/utils_test.go
- api/test/e2e/route_with_management_fileds_test.go
- docs/api/api.md
fix #861
1. Support search route by label.
> feat: support search route by label

- web/cypress/integration/route/create_and_delete_route.spec.js
___
create_and_delete_route case used the wrong way to locate prometheus button
> fix: create_and_delete_route used wrong way to locate plugin button

- web/src/pages/Route/components/Step1/RequestConfigView.tsx
- web/src/pages/Route/transform.ts
> feat: use selector to choose methods

- api/filter/schema.go
- api/test/e2e/route_with_management_fileds_test.go
> fix: not allowed to specify `create_time` and `update_time` when create/edit route, service, upstream and consumer

- Dockerfile
Related to  #1145 .
___
- Description
For now, the `Dockerfile` in master branch fetches the codes from release `v2.0` for building docker images. This would lead to uses could not get the latest code for developing or testing. IMHO, the release tag could be used here only for the Dockerfile defined in tag `v2.0` or `v2.0` branch.
- How to fix?
This PR is going to set the variable `APISIX_DASHBOARD_VERSION ` to `master`, and then we can use the latest code from master branch, as expected.
> fix: fetch code from master branch instead of v2.0 in Dockerfile

- web/src/pages/Plugin/List.tsx
- web/src/pages/Plugin/PluginMarket.tsx
- web/src/pages/Plugin/service.ts
> fix(FE): delete global plugin failed

- Makefile
- api/cmd/managerapi.go
- api/internal/conf/conf.go
- api/internal/log/zap.go
- api/test/shell/cli_test.sh
Fixes #1147 .
___
- Description
Running the prebuilt `manager-api` under non-default directory may lead to failed to start, see #1147 for details. This is mainly caused by the `-p` flag of `manager-api` is not worked as expected.
- How to fix?
Introduce a new value `test` for `ENV` environment to indicates the program is running a unit testing. If `ENV` is set to `test`, the original `init()` functions are retained, otherwise we explicitly calling `InitConf()` and `InitLogger()` functions to  initialization, right after receiving the input `WorkDir` parameter via `-p` flag. This would ensure configs and logger could be initialized just …
> fix(cli): support running manager-api cmd in non-default diretory

- Makefile
- api/build.sh
Fixes #1185 .
___
- Description
As described in #1185 , currently running `make api-run` cannot show out the relevant `Version` and `GitHash` details. The reason is not setting `-ldflags` for `go run` command.
- How to fix?
This PR is going to add missing output values for `api-run`, via running an enhance version of `api/build.sh`. The new build script could support the dry-run mode with simply running `go run` command.
> fix: Support version/githash for make api-run command

- api/internal/filter/authentication.go
- api/test/e2e/authentication_test.go
Fixes #1204 .
___
- Description
If the request to manager-api does not provide a valid authentication token, manager-api will panic. Please see #1204 for details.
- How to fix?
This PR is going to add an additional check that if `token` is `nil`. In the meantime, relative e2e test cases are also committed.
Any feedback is welcome. Thanks.
> fix: well handle with malformed auth token in request header

- api/internal/core/entity/entity.go
- api/test/e2e/base.go
- api/test/e2e/server_info_test.go
Fixes #1176 .
___
- Description
The empty values of `create_time` and `update_time` should not be returned from server_info interface provided by manager-api . Please see #1176 for details.
**Note**:
This PR was previously proposed in #1192 , I could not be able to reopen that PR due to my fault operation after closed it. @nic-chen @liuxiran left their opinions, pls see https://github.com/apache/apisix-dashboard/pull/1192#issuecomment-753858234 and https://github.com/apache/apisix-dashboard/pull/1192#issuecomment-753972035 . 
Firstly I agreed with @nic-chen and @liuxiran for their perfect solutions for all entities. While after some …
> fix: Set create_time/update_time as omitempty

- api/internal/handler/route/route.go
- api/internal/handler/route/route_test.go
As the preparation for release v2.3, this PR is going to cherry-pick 3f8060ead988364972bb2a23f2bedd0dcb1e6ecd from master branch to v2.3 branch . Regarding to the details, please refer to #1207 . 
Noted that the FE counterpart of the bugfix (#1189) has already been merged into v2.3, no need for cherry-pick.
> fix(be): search by status on the route list page is invalid (backport to v2.3)

- .github/workflows/backend-cli-test.yml
- .github/workflows/backend-e2e-test.yml
- .github/workflows/backend-unit-test.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy-with-docker.yml
- .github/workflows/frontend-e2e-test.yml
- .github/workflows/gitleaks.yml
- .github/workflows/go-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/release-test.yml
- .github/workflows/spellchecker.yml
- .github/workflows/test-frontend-multiple-node-build.yml
___
As the preparation of v2.3 release, we need to continuously backport hot bugfixs to `v2.3` branch, so enable CI process at v2.3 branch would help us keep the release more stable. 
Since v2.3 will not be a LTS version, which means there will no activities in v2.3 branch after release v2.3, so this PR is going to use the single `v2.3` for all branch configurations.
> feat(release): Enable CI trigger for v2.3 branch

- api/build-tools/schema-sync.lua
As the preparation for release v2.3, this PR is going to cherry-pick b2d8e0f from master branch to v2.3 branch. Regarding to the details, please refer to #1221 .
> fix: sync the preload packages in schema-sync.lua (#1221)(backport to v2.3)

- web/src/pages/Route/components/DebugViews/DebugDrawView.tsx
___
- Description
1 debug a route: http method POST, with bodyparams
2 change http method to GET, click button `Send`, error occured
- how to fix
GET/HEAD request should not contain bodyparams
> fix: debug page error occured when change method from post to get when post contains bodyparams

- web/src/pages/Route/components/Step1/MatchingRulesView.tsx
- fix #1044
___
- Description
Incomplete label display when create rule in route step1 page
- How to fix?
I have updated MatchingRulesView.tsx to make the Incomplete label display  as expected behavior when create rule in route step1 page
> fix: incomplete label display #1044

- web/cypress/integration/plugin/schema-smocktest.spec.js
___
- Description
Schema Smoke test unstable.
- How to fix?
1. Add timeout and force attributes to the click event.
2. Narrowing the dom node lookup.
___
> feat(FE): enhance plugin schema smoke test

- api/conf/schema.json
- api/internal/core/entity/entity.go
- api/internal/handler/global_rule/global_rule_test.go
- api/test/e2e/global_rule_test.go
- api/test/e2e/go.sum
fix #1143 , taking charge of the manager-api part.
___
As #1143 comes to a conclusion that `create_time` and `update_time` are needed for global_rule entity. This PR is going to  add the two fields and relevant test cases. 
**Note:**
Cause manager-api will validate the schema defined in `schema.json` right before writing to etcd, current test cases will always fail due to the `additionalProperties` for `GlobalRule` is `false`. This PR can only be marked as ready-to-view util the schema is updated from apache/apisix project.
> feat: add create_time/update_time for global_rule

- .github/workflows/lint.yml
- api/test/docker/apisix_config.yaml
- api/test/docker/apisix_config2.yaml
Due to the ASF's policies changing we cannot use the original GitHub Actions for linting as they are not approved
Lint some YAML
refs https://github.com/apache/apisix/pull/3196
___
- Description
- How to fix?
___
___
> fix(CI): Update lint workflow so that the Markdown and YAML linters run

- api/internal/handler/consumer/consumer_test.go
- api/internal/handler/global_rule/global_rule_test.go
- api/internal/handler/server_info/server_info_test.go
(#1281)
___
- Description
Set get called false in the declaration so that we can check the value of `getCalled` accurately if the mock function is called.
> fix: set get called false in the declaration 

- api/cmd/managerapi.go
- api/go.mod
- api/go.sum
- api/internal/filter/authentication.go
- api/internal/filter/authentication_test.go
- api/internal/route.go
- api/test/e2e/authentication_test.go
fix #1295
___
chore: move the authentication middleware into droplet framework. And add the middleware unit test.
___
Added.
> chore: move the authentication middleware into droplet framework 

- api/internal/core/store/store.go
- api/internal/core/store/store_mock.go
- api/internal/core/store/store_test.go
- api/internal/handler/route/route.go
- api/internal/handler/route/route_test.go
- api/internal/handler/service/service.go
- api/internal/handler/service/service_test.go
- api/internal/handler/ssl/ssl.go
- api/internal/handler/ssl/ssl_test.go
- api/internal/handler/upstream/upstream.go
- api/internal/handler/upstream/upstream_test.go
- api/test/e2e/route_test.go
- api/test/e2e/service_test.go
- api/test/e2e/ssl_test.go
- api/test/e2e/upstream_test.go
Related to https://github.com/apache/apisix-dashboard/issues/1154 .
This PR is only going to support HTTP POST method for returning data. In order to completely fix #1154 , we also need to fix that for HTTP PUT methods. I will commit another PR for that soon.
___
As mentioned in #1154 , when creating an object via `POST` method in manager-api, there is no way to refer to that new object for API caller. This PR is going to additionally return all the object data stored in etcd back. See the following example:
Request sent to manager-api:
```
$ curl http://127.0.0.1:9000/apisix/admin/routes -H 'X-API-KEY: …
```
> feat: return back the data just created via POST method in manager API

- api/internal/core/store/store.go
- api/internal/core/store/store_mock.go
- api/internal/core/store/store_test.go
- api/internal/filter/recover.go
- api/internal/handler/consumer/consumer.go
- api/internal/handler/global_rule/global_rule.go
- api/internal/handler/label/label.go
- api/internal/handler/route/route.go
- api/internal/handler/server_info/server_info.go
- api/internal/handler/service/service.go
- api/internal/handler/ssl/ssl.go
- api/internal/handler/upstream/upstream.go
___
pass context for function `Get` and `List`, which is convenient to pass custom parameters or other data in custom development
> feat: pass context for `Get` and `List`

- api/internal/core/store/store.go
- api/internal/core/store/store_mock.go
- api/internal/core/store/store_test.go
- api/internal/handler/consumer/consumer.go
- api/internal/handler/consumer/consumer_test.go
- api/internal/handler/global_rule/global_rule.go
- api/internal/handler/global_rule/global_rule_test.go
- api/internal/handler/route/route.go
- api/internal/handler/route/route_test.go
- api/internal/handler/service/service.go
- api/internal/handler/service/service_test.go
- api/internal/handler/ssl/ssl.go
- api/internal/handler/ssl/ssl_test.go
- api/internal/handler/upstream/upstream.go
- api/internal/handler/upstream/upstream_test.go
- api/test/e2e/consumer_test.go
- api/test/e2e/global_rule_test.go
- api/test/e2e/route_test.go
- api/test/e2e/service_test.go
- api/test/e2e/ssl_test.go
- api/test/e2e/upstream_chash_query_string_arg_xxx_test.go
Related to https://github.com/apache/apisix-dashboard/issues/1154 .
___
- Description
As described in #1154 , when manipulating an object via PUT/PATCH method in manager-api, there is no data returned.
- How to fix?
In order to get along with APISIX Admin API, this PR is going to additionally return all the object data back for  PUT or PATCH methods. 
> This PR is also a counterpart of https://github.com/apache/apisix-dashboard/pull/1277 , will completely revolve #1154 .
> feat: Add returning value for HTTP PUT and PATCH methods

- web/cypress/integration/route/search-route.spec.js
___
changed the search-route test,  add domSelector and data
> feat: add domSelector and data for search-route

- api/internal/core/storage/etcd.go
- api/internal/core/storage/storage.go
- api/internal/core/store/store.go
- api/internal/core/store/store_test.go
Fixes #1357 .
___
- Description
As described in #1357 , we decide to move the skip logic to Storage from Store. This PR is going to achieve that.
- How to fix?
Remove `Skipped` field from `Event` object and Storage will eliminate the invalid data before sending to Store anymore.
> fix: Skip the data directly in Storage level

- web/src/pages/Route/components/Step1/MetaView.tsx
fix:#1349
___
- Description
add maxlength={256} to Input.TextArea
- How to fix?
I've updated  Input.TextArea with showCount maxLength={256}.
> fix: add maxlength={256} to Input.TextArea

- api/go.mod
- api/go.sum
fixes #1353 
- How to fix?
Upgraded version gjson to `v1.6.7`
> build: upgrade gjson to v1.6.7

- .github/workflows/backend-cli-test.yml
- .github/workflows/backend-unit-test.yml
- Makefile
close #950
___
- Description
some test cases rely on Lua and lib `dag-to-lua`,  without the lib will fail.
- How to fix?
when run `make api-test`, should check dag-to-lua dependencies, if the dependencies are not installed, we will download and install.
> fix: make api-test failed

- api/internal/handler/data_loader/route_export.go
- api/internal/handler/data_loader/route_export_test.go
- api/test/e2e/route_export_test.go
#1383 
___
- When exporting route data, the current logic will export empty swagger data when the route data is null or there is no route data. Whether to add judgment will directly return an error.
- How to fix?
When null characters are passed in, routeid is not passed in, or all routeid data is exported, there is no data in the database, and an error should be reported directly.
>  fix: When exporting route, whether the parameter is empty or not

- web/cypress/integration/lang/switch-language.spec.js
- web/cypress/integration/plugin/create-edit-delete-plugin.spec.js
- web/cypress/integration/plugin/schema-smocktest.spec.js
- web/cypress/support/commands.js
resolve #1156 
add edit the plugin test
> test: add edit the plugin

- api/internal/core/entity/entity.go
- api/internal/handler/route/route.go
- api/internal/handler/route/route_test.go
- api/test/e2e/route_with_script_luacode_test.go
Related to #1085 .
___
As discussed in #1085 with @spacewander , this PR is going to add a new field `script_id` in `Route` entity to support for debug and optimization(cache) in the future. For now, we could assume that `script_id` will be always equal to the `id` of `Route` entity.
___
Yep, backend tests and backend e2e tests are added.
> feat: Add script_id field in Route entity

- docs/back-end-e2e.md
- docs/develop.md
fix #1380 
___
- Add back-end E2E test environment construction and test steps
> docs: Add back end E2E test document

- .github/workflows/deploy-with-docker.yml
- Dockerfile
- api/test/shell/docker_deploy_test.sh
Fixes #1350 .
___
- Description
At previous manager-api build phase in Dockerfile, the ldflags of `github.com/apisix/manager-api/cmd.Version` and `github.com/apisix/manager-api/cmd.GitHash` are missing. This lead to the no `Version` output when running `manager-api`, as described in #1350 .
- How to fix?
Add missing `ldflags` in Dockerfile. For simplicity, this PR is going to reuse the existing built script `./api/build.sh` to compile out the binary. 
In addition, this PR will also reduce the usage of `RUN` commands for smaller image size.
- Additional 
FYI, since there is no `.githash` or `.git/` within the artifact downloaded from …
> fix: Add version ldflags for building manager-api in Dockerfile

- api/internal/handler/service/service.go
- api/internal/handler/service/service_test.go
- api/test/e2e/service_test.go
#1392 
___
- Description
I find that the jsonpatch(github.com/api7/go-jsonpatch) used by upstream and service when calling the patch method is still the old package,updated to github.com/evanphx/json-patch/v5
- How to fix?
Modify the service to use the new JSON patch package
> fix(be): Modify the service to use the new JSON patch package

- .github/workflows/backend-e2e-test.yml
- .github/workflows/deploy-with-docker.yml
- api/test/docker/docker-compose.yaml
- docs/back-end-e2e.md
close #698 
___
- use the original conf/config.yaml + sed to replace `api/test/docker/manager-api-conf.yaml`
- manage-api-conf.yaml Keep the local test for use, and then put the E2E test step into the makefile for execution, and then delete it.
> chore: Use the original conf/config.yaml + sed to replace `api/test/docker/manager-api-conf.yaml`

- web/cypress/integration/route/create-route-with-upstream.spec.js
resolve #1408 
___
- Description
`create-route-with-upstream.spec` Unstable
- How to fix?
___
> fix(FE): create-route-with-upstream.spec test

- .github/workflows/backend-e2e-test.yml
- api/test/docker/docker-compose.yaml
___
- Description
directly use the path in the `apisix-docker` github repo as the context, resulting the `Dockerfile` not being found.
- How to fix?
first download the `Dockerfile` in the github repo to the CI env local, using the local directory as the context
> fix: docker build failed in backend e2e test CI

- api/internal/core/storage/etcd.go
- api/internal/core/store/store.go
- api/internal/utils/runtime/runtime.go
- api/internal/utils/runtime/runtime_test.go
close #838
___
- Description
Manager API may crash without any logs.
In gin, we use filter.RecoverHandler() to prevent crash.
But we can not control the exceptions in other go-routines.
- How to fix?
add defer recover() for go routines to prevent abnormal crash
> fix: add defer recover for go routines to prevent abnormal crash

- api/internal/filter/authentication.go
- api/internal/handler/tool/tool.go
- api/test/e2e/version_test.go
- api/test/shell/cli_test.sh
- 
https://github.com/apache/apisix-dashboard/pull/1408#discussion_r570317906
change the /version to /apisix/admin/tool/version
> fix: change the /version to /apisix/admin/tool/version

- .github/workflows/backend-e2e-test.yml
- api/cmd/managerapi.go
- api/conf/conf.yaml
- api/internal/conf/conf.go
- api/internal/filter/ip_filter.go
- api/internal/filter/ip_filter_test.go
- api/internal/route.go
- api/test/shell/cli_test.sh
close #680
___
support IP allow list for Manager API
> feat: support IP allow list

- web/cypress/integration/settings/settings-smoketest.spec.js
___
- Description
https://github.com/apache/apisix-dashboard/pull/1435/checks?check_run_id=1840149946
Recently this test case failed many times, I tried locally and the same problem reproduced when the `https://apisix.apache.org/` is hard to visit, when I access the website smoothly, this case can also passed smoothly
* Many people have encountered this problem and there has not seem to be a good solution yet, see
https://github.com/cypress-io/cypress/issues/3427
* I tried to change the url from `https://apisix.apache.org/` to `http://localhost:8000/routes/list` the internal address in dashboard, run the case as many times as possible, it worked well
so I change the url to make …
> fix: change setting smoke test validURL to http://localhost:8000/routes/list

- api/conf/schema.json
- web/cypress/fixtures/plugin-dataset.json
Co-authored-by: litesun <7sunmiao@gmail.com>
___
`2.3` is the version of APISIX that matches the upcoming release 2.4 of dashboard, we need this PR for sync the JSON schema within APISIX `2.3`.
`master`
commit: https://github.com/apache/apisix-dashboard/commit/5348579f0c5e1de2e0e664dfb6984ab35ca02329 
PR: https://github.com/apache/apisix-dashboard/pull/1445
`v2.4`
> backport: chore: sync JSON Schema from APISIX version 2.3 (#1445)

- web/cypress/integration/route/create-route-with-upstream.spec.js
___
- Description
1. https://github.com/apache/apisix-dashboard/runs/1843264349
I reproduced this failure locally, the error occurred due to It has not changed to step two after click `Next` button in step one  
Solution:
add `cy.get(this.domSelector.name).should('value', data.route_name);` to ensure edit page has ready loaded
add `{force: true}` to `Next` button click to ensure the button clicked
2. https://github.com/apache/apisix-dashboard/pull/1445/checks?check_run_id=1847652754
I reproduced this failure locally, the error occurred due to It has stop on login page after `should create an upstream` run off, I tried to merge `should enter the Route creator` `should disable …
> test: make create route with upstream test cases stable

- web/cypress/integration/route/online-debug.spec.js
- web/package.json
- web/src/pages/Route/components/DebugViews/DebugDrawView.tsx
- web/yarn.lock
___
- Description
> This part of the regular expression may cause exponential backtracking on strings starting with '0' and containing many repetitions of '0'.
This issue originated from https://github.com/apache/apisix-dashboard/pull/1417#issuecomment-772585704, which caused The performance on the UI : when type `000` to debug url, it will passed the reg test
- How to fix?
use [url-regex-safe](https://github.com/niftylettuce/url-regex-safe) instead of manually debug url regexp to test the debug url
___
add test cases to test `000` and empty url
> fix: change manually debug url regexp to lib url-regex-safe

- api/test/shell/cli_test.sh
___
- Description
- How to fix?
`stop` is an asynchronous task, so it needs to sleep to wait, uniformly using 6 sec.
> fix: cli test failed

- web/cypress/fixtures/data.json
- web/cypress/fixtures/selector.json
- web/cypress/integration/user/login.spec.js
- web/src/pages/User/Login.tsx
resolve #1311 
___
You can press Enter to log in.
___
> feat: Press Enter key can trigger the Login button

- web/cypress/integration/metrics/metrics-smoketest.spec.js
- web/src/pages/Metrics/Metrics.tsx
- web/src/pages/Metrics/locales/en-US.ts
- web/src/pages/Metrics/locales/zh-CN.ts
added tip on the Metrics page, to tell users that the Metrics page should be used with Grafana Share URL, and it's stored in local only.
NOTE: this is only a tip, no need to add a testcase.
> feat: added tip on the Metrics page

- web/package.json
- web/src/components/RawDataEditor/RawDataEditor.tsx
- web/src/components/RawDataEditor/index.tsx
- web/src/components/RawDataEditor/locales/en-US.ts
- web/src/components/RawDataEditor/locales/zh-CN.ts
- web/src/locales/en-US.ts
- web/src/locales/en-US/component.ts
- web/src/locales/zh-CN.ts
- web/src/locales/zh-CN/component.ts
- web/src/pages/Consumer/List.tsx
- web/src/pages/Route/List.tsx
- web/src/pages/Service/List.tsx
- web/src/pages/Upstream/List.tsx
> feat: add rawDataEditor for route, consumer, upstream and service

- api/test/docker/docker-compose.yaml
___
- Description
can't pull skywalking image in ci
```
Pulling skywalking (apache/skywalking-oap-server:)...
manifest for apache/skywalking-oap-server:latest not found: manifest unknown: manifest unknown
```
https://github.com/apache/apisix-dashboard/pull/1504/checks?check_run_id=1994180070#step:6:1409
- How to fix?
use the specified version of `skywalking`
> ci: use the specified version of `skywalking`

- api/internal/handler/ssl/ssl.go
- api/internal/handler/ssl/ssl_test.go
close #1476 
___
- Description
When an api request comes in, the droplet framework will bind the parameters first, and the go array cannot be bound to the struct, which leads to this bug
- How to fix?
Change the array parameter to an object.
> fix: cannot unmarshal array into go value of type

- api/test/e2enew/upstream/upstream_test.go
___
- Description
upstream_test.go Add respbody error assertion and defer resp.Body.Close ()
The old way of writing, if in resp.Body.close () trigger assertion before execution, which will cause resp.Body Not closed, resulting in a memory leak
> fix: Add upstream_test respbody error assertion and defer resp.Body.Close ()

- .github/workflows/backend-e2e-test.yml
- .github/workflows/backend-unit-test.yml
- .github/workflows/frontend-e2e-test.yml
___
- Description
- How to fix?
___
___
___
> feat: add frontend e2e report on pr comment

- web/src/pages/Route/service.ts
___
- Description
The API needs to receive `{ hosts }` instead of `hosts`.
> fix: use hosts object instead of pure data

- api/test/e2enew/server_info/server_info_suite_test.go
- api/test/e2enew/server_info/server_info_test.go
#1500
___
-  Rewrite e2e test(server_info) with ginkgo
> feat: rewrite e2e test(server_info_test) with ginkgo

- web/cypress/fixtures/selector.json
- web/cypress/integration/route/import_export_route.spec.js
- web/cypress/integration/route/online-debug.spec.js
- web/cypress/integration/route/search-route.spec.js
#1538 
___
- Description
e2e failed
- How to fix?
Enhanced stability, modified the domSelector name for some tests.
___
> test: update test

- web/src/components/Plugin/PluginDetail.tsx
- web/src/components/Plugin/PluginPage.tsx
- web/src/pages/Plugin/List.tsx
resolves #1548 
Now, clicking on the masked area of the plugin drawer does not close it.
> feat: disable closing plugin drawer on clicking the mask

- api/conf/conf.yaml
- api/internal/conf/conf.go
resolves #682 
___
Supports changing the number of os threads attached to the goroutines.
For performance reason, if in the configuration file, the defined `max_cpu` is greater than the number of available cpu cores (including hyperthreading), the `manager api` will stick to the max available cores. As it has a certain limit to boost the performance since the context switching of goroutines from the same os thread is a lot faster than goroutines from different threads.
> feat: supports changing number of executing cpu cores for manager api

- web/cypress/integration/pluginTemplate/create-plugin-template-with-route.spec.js
___
fix FE ci failed
comment: https://github.com/apache/apisix-dashboard/pull/1570#issuecomment-795670862
Fe ci repair should submit new PR and should not be mixed up.
> fix: fix fe ci failed

- web/package.json
___
- Description
When we run the `yarn cypress:open-dev ` on Windows, it will occur the 'CYPRESS_SERVE_ENV' is not recognized as an internal or external command error.
- How to fix?
Add the `cross-env` in the npm script.
> fix: fix CYPRESS cross platform env error

- .github/workflows/make-build.yaml
- api/internal/core/entity/entity.go
- api/test/docker/docker-compose.yaml
- api/test/shell/cli_test.sh
- web/cypress/fixtures/export-route-dataset.json
___
- Description
`Vars` in  struct `Route` uses interface{} as the type, which makes it impossible to omit an empty array.
As a result, after APISIX uses the new version of `lua-resty-radixtree`, The routes with empty array `vars` cannot be matched
- How to fix?
uses []interface{} instead. and also fix some small potential unstable issues
> fix: CI failed

- web/cypress/fixtures/export-route-dataset.json
- web/src/components/Upstream/UpstreamForm.tsx
- web/src/components/Upstream/constant.ts
Fix #1565
___
- Description
- How to fix?
Change the upstream timeout unit to s.
> fix: fix the upstream timeout unit

- api/test/e2enew/route/route_with_plugin_proxy_rewrite_test.go
#1500
___
-  Rewrite e2e test(rewrite-e2e-test-route-with-proxy-test) with ginkgo
> feat: rewrite e2e test(rewrite-e2e-test-route-with-proxy-test) with ginkgo

- api/internal/handler/handler.go
- api/internal/handler/handler_test.go
- api/internal/handler/route/route.go
- api/internal/handler/route/route_test.go
- api/internal/handler/service/service.go
- api/internal/handler/service/service_test.go
- api/internal/handler/upstream/upstream.go
- api/internal/handler/upstream/upstream_test.go
- api/test/e2e/route_export_test.go
- api/test/e2e/route_import_test.go
- api/test/e2e/route_with_management_fileds_test.go
- api/test/e2e/route_with_plugin_http_logger_test.go
- api/test/e2enew/route/route_test.go
- api/test/e2enew/route/route_with_priority_test.go
- api/test/e2enew/service/service_test.go
- api/test/e2enew/upstream/upstream_test.go
#1595
___
- Description
When creating route, server and upstream in the Dashboard, the FE queries whether the same name exists through API, and does not run the addition if it exists. But the backend lacks this limitation.
- How to fix?
Add a judgment on whether the name exists in the backend, if it exists, it is not allowed to create or update.
> fix: check name existed when creating or updating a resource

- api/test/e2enew/route/route_with_plugin_prometheus_test.go
#1500
___
-  Rewrite e2e test(rewrite-e2e-test-route-with-prometheus-test) with ginkgo
> feat: rewrite e2e test(rewrite-e2e-test-route-with-prometheus-test) with ginkgo

- web/cypress/integration/route/import_export_route.spec.js
- web/cypress/integration/route/online-debug.spec.js
related #1605 
___
fixed unstable front-end tests.
> fix: unstable front-end tests

- api/internal/handler/service/service.go
- api/internal/handler/service/service_test.go
- api/test/e2enew/service/service_test.go
Now, when deleting a service, we don't check whether there is a route using it.
This may lead to the DP error if the user deletes the service by mistake.
So, we should check if the service is using by route when deleting.
If the service is using, we return 400 to guarantee the DP works well.
___
Added.
___
> feat: check if the service is used by route when deleting

- api/internal/handler/route_online_debug/route_online_debug.go
- api/test/e2enew/route_online_debug/route_online_debug_test.go
- web/cypress/integration/consumer/create_and_delete_consumer.spec.js
- web/cypress/integration/route/search-route.spec.js
___
- Description
There is a bug in the use process. The user writes the `Content-type` to the `header-params` to forward the content type of the URL. The old logic uses the `req.Header.Add` method to generate multiple `Content-type` values, which leads to the failure of the forwarding request.
- How to fix?
use `req.Header.Set` To override the ·Content-type· and ensure that the value is unique。
> fix: (route_online_debug)Change the appended Content-type data to overlay to ensure that the Content-type is unique

- api/test/docker/docker-compose.yaml
___
- Description
APISIX has remove consumer.id, see:
https://github.com/apache/apisix/pull/3868
This is an incompatible modification, causing some of the current E2E test cases to fail
- How to fix?
use APISIX 2.4 to run backend E2E test
> fix: use APISIX 2.4 to run backend E2E test

- web/src/components/Upstream/UpstreamForm.tsx
resolves #1555 
https://user-images.githubusercontent.com/41498427/111036505-84c45000-8445-11eb-924f-bf013682becd.mp4
Thank You.
> feat: searching upstream by users input while creating new routes

- web/src/pages/Upstream/List.tsx
- Related issues 
Fix #1602 
___
- Description
Use and `Space` to add each button's margin, and remove inline margin style.
> fix: fix the button margin space

- api/test/docker-deploy/docker-compose.yaml
- api/test/docker/docker-compose.yaml
`quay.io/coreos/etcd` is down
uses `gcr.io/etcd-development/etcd` as  ETCD container registry, instead of `quay.io/coreos/etcd`
**Checklist:**
> fix: ETCD container registry

- web/cypress/integration/consumer/create_and_delete_consumer.spec.js
- web/cypress/integration/pluginTemplate/create-edit-delete-plugin-template.spec.js
- web/cypress/integration/pluginTemplate/create-plugin-template-with-route.spec.js
- web/cypress/integration/route/create-edit-delete-route.spec.js
- web/cypress/integration/service/edit-service-with-upstream.spec.js
related #1605  #1633  #1634
___
fixed CI error: 
Update front-end E2E tests to enhance stability based on CI errors.
> test: enhanced test stability

- api/test/e2enew/route/route_with_plugin_cors_test.go
> feat: rewrite e2e test(test-e2e-route-with-plugin-CORS) using ginkgo

- api/test/e2enew/route/route_with_methods_test.go
> feat: rewrite e2e test(test-e2e-route-with-method) using ginkgo

- api/internal/handler/data_loader/route_export.go
- api/internal/handler/data_loader/route_export_test.go
- api/test/e2e/route_export_test.go
- web/cypress/fixtures/export-route-dataset.json
1. Fixed the bug that when creating route, the methods field is nil or [] and the data cannot be exported.
2. When there is no plugin data in the route, the empty field is not exported.
fix/resolve #1668 
**Checklist:**
> fix: unable to export route with nil methods field

- web/src/pages/Upstream/locales/zh-CN.ts
Error Generate:
Go to chinese lang upstream, its shows `page.upstream.configure` in title in place of 'page.up`
in place of `配置上游`
**Checklist:**
> fix: ERROR page.upstream.configure fixed

- .gitignore
- api/internal/handler/route/route.go
- web/config/routes.ts
- web/cypress/integration/route/create-edit-duplicate-delete-route.spec.js
- web/src/locales/en-US/component.ts
- web/src/locales/zh-CN/component.ts
- web/src/pages/Route/Create.tsx
- web/src/pages/Route/List.tsx
Why submit this pull request?
Support duplicate one existing Route  https://github.com/apache/apisix-dashboard/issues/1487
New feature or improvement
1: duplicate button from route list
2: check duplicate name from POST route api
Describe the details and related test reports.
1:Click duplicate button from the router list, the address will be  `routes/:rid/duplicate`
2: update the name to make sure it's no duplicated
3: submit data, return to the list. The new route will be there
> feat:Support duplicate one existing Route

- .github/workflows/frontend-e2e-test.yml
- .github/workflows/frontend-plugin-e2e-test.yml
- web/cypress.json
- web/package.json
Currently, front-end e2e CI takes around 40+ minutes to run through. This PR is used to reduce the front-end e2e time by about 20mins.
resolves #1614 
**Checklist:**
> chore: reduce FE e2e ci time

- web/cypress/integration/pluginTemplate/create-edit-delete-plugin-template.spec.js
- web/src/pages/PluginTemplate/Create.tsx
While checking #1719 , another bug happened, `proxy-rewrite` plugin can still be configed in `plugin template` page.
Remove `proxy-rewrite` out of  create plugin template config step2 , just keep the same as the create route step3 does.
fix/resolve None
**Checklist:**
> fix: remove proxy-rewrite plugin out of create plugin template config view

- api/test/docker/docker-compose.yaml
Due to the unavailability of the luarocks service, the image from the dockerfile build APISIX failed, which affected the back-end e2e test. So instead use the image on the docker hub to run the e2e test environment.
> fix: use image of APISIX on docker hub instead of build from dockerfile

- netlify.toml
Hi, the web is a Single Page Application, and we use `Netlify` to deliver it. When we visiting the Preview page & refresh, it will throw 404 pages, that's the natural behavior of SPA. This PR aims to support 404 fallbacks, so we could refresh as other web applications.
**Checklist:**
> chore: support SPA 404 fallback

- api/internal/utils/utils.go
Use `strconv.ParseUint` instead of `strconv.Atoi` and specify the bit size.
**Checklist:**
> fix: incorrect conversion between integer types

- web/src/pages/SSL/List.tsx
- web/src/pages/SSL/components/CertificateForm/index.tsx
- web/src/pages/SSL/components/Step1/index.tsx
- web/src/pages/SSL/locales/en-US.ts
- web/src/pages/SSL/locales/zh-CN.ts
> chore: added fields for SSL

- web/cypress/integration/route/online-debug.spec.js
Due to we merged one PR about the test on OnlineDebug hours ago, it failed due to some changes from the master branch. We need to find the correct element, and everything will go well.
**Checklist:**
> fix: online debug test case

- web/src/pages/User/components/LoginMethodPassword.tsx
user login request should remove its own prefix option
**Checklist:**
> fix: user login request should remove its own prefix option

- web/src/locales/en-US/component.ts
- web/src/pages/Upstream/locales/en-US.ts
Signed-off-by: Eric Shen <ericshenyuhao@outlook.com>
There is an in inconsistent display name on the Route, Upstream and SSL pages:
* Route page
* Upstream page
* SSL page
* Consumer page
So i modified `component.global.updateTime` and `page.upstream.list.edit.time` to keep the display name align as **Update Time**.
No related issue.
**Checklist:**
> fix: inconsistent displayname of updatetime under EN locale

- web/cypress/fixtures/export-route-dataset.json
- web/cypress/integration/route/create-edit-duplicate-delete-route.spec.js
- web/cypress/integration/route/online-debug.spec.js
- web/src/pages/Route/components/Step1/MatchingRulesView.tsx
- web/src/pages/Route/constants.ts
- web/src/pages/Route/locales/en-US.ts
- web/src/pages/Route/locales/zh-CN.ts
- web/src/pages/Route/service.ts
- web/src/pages/Route/transform.ts
- web/src/pages/Route/typing.d.ts
- web/src/typings.d.ts
According to https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L335
**Checklist:**
> feat: added sample for vars in Route & improve Typings

- web/src/components/Upstream/components/Nodes.tsx
- web/src/pages/Upstream/locales/en-US.ts
- web/src/pages/Upstream/locales/zh-CN.ts
Signed-off-by: EricSyh <ericshenyuhao@outlook.com>
The warning message of host form on upstream/services create pages uses raw regexp as below which is unfriendly to users. 
So i modified nodes component under upstream to add an easy-to-understand warning message look like: 
No related issues. 
**Checklist:**
> fix: upstream host form warning message

- web/src/components/Plugin/PluginDetail.tsx
- web/src/components/Upstream/components/active-check/HttpsVerifyCertificate.tsx
> fix: active check & plugin form

- web/cypress/integration/upstream/create_and_edit_upstream_with_no_nodes.spec.js
> @liuxiran FE ci failed after this pr got merged. Could you please take a look, please refer to https://github.com/apache/apisix-dashboard/runs/2430236911. Thanks.
come from: https://github.com/apache/apisix-dashboard/pull/1812#issuecomment-826267363
this pr tried to solve this unstable test case.
None
**Checklist:**
> fix: unstable ci in create_and_edit_upstream_with_no_nodes.spec.js

- api/internal/filter/ip_filter.go
- api/internal/filter/ip_filter_test.go
Now, we use the gin's context.ClientIP.This function will parse the IP from the header `X-Forwarded-For` and `X-Real-Ip`
which will bypass the ipfilter middleware.
Use remote address instead of client ip.
**Checklist:**
> fix: use remote address instead of client ip

- Makefile
Using `curl -so` instead of `wget -P` because `curl` is more general.  
**Checklist:**
> build: using curl command instead of wget

- web/src/pages/Route/Create.tsx
clear the route name blank when duplicate route.
fix/resolve #1703 
**Checklist:**
> fix: improve the Duplicate Route feature

- web/cypress/integration/route/create-route-with-cors-form.spec.js
- web/src/components/Plugin/PluginDetail.tsx
- web/src/components/Plugin/UI/cors.tsx
when I submitted default cors plugin configure in form mode, a validation error occured:
the error shows that `allow_origins_by_regex` should have at least 1 character.
*  Reason
schema of `cors` plugin:
```json
{
"properties": {
...
"allow_origins_by_regex": {
"description": "you can use regex to allow specific origins when no credentials,for example use [.*\\.test.com] to allow a.test.com and b.test.com",
"items": {
"maxLength": 4096,
"minLength": 1,
"type": "string"
},
"minItems": 1,
"type": "array",
"uniqueItems": true
},
},
"type": "object"
}
```
shows that `allow_origins_by_regex` is not a required item, but when …
> fix: default cors plugin formdata validation error

- api/cmd/managerapi.go
- api/internal/core/store/store.go
- api/internal/core/store/store_test.go
- api/internal/utils/pid.go
- api/test/shell/cli_test.sh
5. Closing of all opened resource has been put into deferred execution. So incase any panic occurs during runtime, the respective closers of the resource gets executed safely. Till now, for panics, the main goroutine was getting closed ungracefully.
6. Detailed error description if etcd contains corrupted data and exit with nonzero error code.
reopening #1705 
closes #1684 
**Checklist:**
> fix: efficient error handling in manager-api including graceful shutdown, self contained methods.

- api/internal/handler/route/route.go
- api/test/e2enew/route/route_with_plugin_orchestration_test.go
This PR is to fix this situation:
when creating the route with the script, but without the id.The original logic will return the `key is required`.
Fix the situation: 
When creating the route with the script, but without the id.The original logic will return the `key is required`.
**Checklist:**
> fix: generate an uid when post a route without id

- web/src/pages/Route/List.tsx
Now the Route page will support all view ports and won't get messed up due to different viewports
fix/resolve #1815 
**Checklist:**
> fix: route page Protable

- web/cypress/integration/user/login.spec.js
> chore: refactored test login.spec.js

- web/cypress/integration/route/create-route-with-proxy-mirror-form.spec.js
> chore: refactored test create-route-with-proxy-mirror-form.spec.js

- web/src/components/Plugin/UI/cors.tsx
- web/src/components/PluginFlow/constants.ts
This PR aims to fix the broken Route creator, this issue is caused by the invalid import path, and when run building, we don't have a checker to check this.
To prevent this occasional case, we may have `Husky` enabled and check paths.
fix https://github.com/apache/apisix-dashboard/issues/1889
**Checklist:**
> fix: incorrect import paths

- web/cypress/integration/dashboard/dashboard-smoketest.spec.js
> chore: refactored test dashboard-smoketest.spec.js

- web/cypress/integration/consumer/create_and_delete_consumer.spec.js
> chore: refactored test create-and-delete-consumer

- docs/en/latest/deploy-with-rpm.md
- docs/en/latest/deploy.md
Users guide.
closes #842 
**Checklist:**
> docs: manager-api as os service

- .github/workflows/backend-e2e-test.yml
- .github/workflows/deploy-with-docker.yml
- .github/workflows/frontend-e2e-test.yml
- .github/workflows/frontend-plugin-e2e-test.yml
- .github/workflows/make-build.yaml
- .github/workflows/test-frontend-multiple-node-build.yml
- .gitmodules
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
Use github official argument to cancel duplicate workflows, to replace deprecated `cancel-workflow-runs`.
Tested for push and PR from [original repo](https://github.com/Yiyiyimu/GithubActionsTest/pull/8) and [forked repo](https://github.com/Yiyiyimu/GithubActionsTest/pull/9)
Ref: https://github.com/apache/apisix/issues/4341
**Checklist:**
> ci: use concurrency to cancel duplicate workflow

- docs/en/latest/USER_GUIDE.md
Fixes broken links for images under `../docs/dashboard/2.5/USER_GUIDE`. 
**Re**: Some specific images are not being populated under `docs/dashboard/2.5/USER_GUIDE` in apisix website & are fetched from the master branch i.e. `apisix-dashboard/blob/master/docs/assets/images` instead of `apisix-dashboard/blob/release/2.5/docs/assets/images` & those images of v2.5 aren't present in master.  
Now those missing images are being hosted via GitHub CDN.
fix/resolve #[358](https://github.com/apache/apisix-website/issues/358)
**Checklist:**
> fix: broken images

- api/cmd/root.go
- api/internal/utils/pid.go
additional flag `-f` or `--force` to force start Manager API with different configuration maybe when a PID file is already existing.
in continuation with #1814 
https://github.com/apache/apisix-dashboard/pull/1814#discussion_r627478821
**Checklist:**
> feat: additional flag to force start manager-api

- api/cmd/root.go
- api/cmd/version.go
- api/internal/core/server/http.go
- api/internal/core/server/server.go
- api/internal/core/server/store.go
- api/test/shell/cli_test.sh
Refactoring the management code of Manager API to help to initialize, start and stop. Reduce redundant code and improve readability.
I created a new `server` module in `internal/core`. 
It will help run according to the process of `NewServer()`->`server.init()`->`Start()`->`Stop()`.
It covers the functions of initializing etcd client, initializing store, initializing route and starting HTTP server.
**Checklist:**
> refactor: server manager

- web/src/components/Plugin/PluginPage.tsx
- web/src/components/Plugin/locales/en-US.ts
Modify some txt tips to correct grammar.
fix/resolve #Modify some txt tips to correct grammar.
**Checklist:**
> docs: modify some txt tips to correct grammar

- web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js
- web/src/components/Plugin/PluginDetail.tsx
- web/src/components/Plugin/service.ts
- web/src/components/Plugin/typing.d.ts
only auth type plugin need to configure
resolve #1975 
**Checklist:**
> fix: only auth type plugin need to configure

- web/cypress/integration/route/import_export_route.spec.js
- web/src/components/Upstream/components/Nodes.tsx
For most scenarios, the weight value of the upstream node is 1, so setting a initial weight value 1 can reduce user input.
fix/resolve
**Checklist:**
> feat: set a initial weight value for the upstream node

- web/src/pages/Consumer/List.tsx
The consumer does not have an id attribute, but the id is used when update consumer, which will result in the creation of an undefined user.
Modified to use `username` for update.
fix #1954 
**Checklist:**
> fix(consumer): fix add undefined user when view

- web/src/components/Upstream/locales/en-US.ts
Fixed i18n in the TCP failure field of the upstream component.
resolve #1959 
**Checklist:**
> fix: i18n for TCP in Upstream

- web/cypress/integration/route/create-route-with-chash-upstream.spec.js
- web/cypress/integration/service/create-service-with-chash-upstream.spec.js
- web/cypress/integration/upstream/create_and_edit_upstream_with_custom_chash_key.spec.js
- web/src/components/Upstream/components/Type.tsx
Fixes #1952
fix/resolve #1952
**Checklist:**
> fix: make service chash key Input inputable and selectable

- web/src/components/Plugin/PluginDetail.tsx
- web/src/components/Plugin/UI/limit-req.tsx
- web/src/components/Plugin/UI/plugin.tsx
The PR will change the plugin under plugin/UI (limit-req), allowing limit-req to dynamically adapt to the back-end json rules.
fix/resolve #1588 
**Checklist:**
> feat(plugin): allowing limit-req to dynamically adapt to the BE rules

- web/cypress/integration/route/search-route.spec.js
- web/cypress/integration/upstream/create_and_delete_upstream.spec.js
- web/src/app.tsx
- web/src/components/Upstream/locales/en-US.ts
In the optional `InputNumber` component of the entire project, when the user chooses not to fill in, the value of the field in the request body is `null`, which will cause a request error.
The correct approach is to delete all fields with `null` values in the request body.
fix #2019 
**Checklist:**
> fix: delete null value in request body

- web/cypress/integration/route/can-skip-upstream-when-select-service-id.spec.js
- web/cypress/integration/route/create-edit-route-with-redirect-plugin.spec.js
- web/src/pages/Route/components/Step1/MetaView.tsx
- web/src/pages/Route/transform.ts
Pass the normal `enable_websocket` state to the API.
fix #1933 
**Checklist:**
> fix: websocket enable in route

- .github/workflows/auto-build-rpm.yml
The package name of apisix-dashboard in CentOS7 has been added with the OS distribution name `el7`, see https://github.com/api7/apisix-build-tools/pull/67 for details. So this PR is going to change the relevant rpm name to `apisix-dashboard-${version}-0.el7.x86_64.rpm` from the original `apisix-dashboard-${version}-0.x86_64.rpm`. This PR will also fix the CI failures due to the stale package name.
**Checklist:**
> ci: add el7 in package name

- api/internal/handler/data_loader/route_export.go
fix/resolve:
avoid nil pointer dereference
**Checklist:**
> fix: avoid nil pointer dereference

- .github/workflows/auto-build-rpm.yml
The apisix-dashboard CI is using the master code of apisix-build-tools for building and packaging. While this would lead to unexpected errors if anything is incompatible. In other words, we should always rely on a stable version. This PR is going to use the `v2.0.0` of apisix-build-tools, which is also heading to the same commit with the latest code of the current master branch.
Related to https://github.com/api7/apisix-build-tools/issues/75.
**Checklist:**
> chore: Use build-tools v2.0.0 instead of master

- .github/workflows/auto-build-rpm.yml
This PR is going to bump apisix-build-tools to v2.1.0, which makes use of the `local_code_path` param to avoid downloading the repository again remotely.
**Checklist:**
> feat: Bump apisix-build-tools to v2.1.0

- docs/en/latest/I18N_USER_GUIDE.md
- web/cypress/integration/route/create-edit-duplicate-delete-route.spec.js
- web/src/pages/Route/components/Step1/MetaView.tsx
- web/src/pages/Route/locales/en-US.ts
- web/src/pages/Route/locales/zh-CN.ts
fix/resolve #2057 
**Checklist:**
> fix: validate rules in Apisix Dashboard is same as Apisix api

- .github/workflows/deploy-with-docker.yml
After refer to https://github.com/docker/buildx/blob/master/docs/reference/buildx_create.md#driver, this PR is going to use `docker-container` driver to replace the `docker` driver, which does not support cache yet. Will fix the CI failures when running `docker buildx bake` at https://github.com/apache/apisix-dashboard/runs/3479593341. 
Fixes #2108.
**Checklist:**
> fix: ci failure for buildx

- .github/workflows/deploy-with-docker.yml
Since #2109 does not completely resolve #2108, this is another solution. This PR is going to create new builder, instead of the default one, to support cache and many other features. See https://docs.docker.com/engine/reference/commandline/buildx_create/ for details.
Fixes #2108.
**Checklist:**
> ci: fix errors due to buildx bake with cache

- web/cypress/integration/route/create-edit-route-with-redirect-plugin.spec.js
- web/src/pages/Route/components/Step1/MetaView.tsx
fix: after enable redirect HTTPS, websocket form field disappeared
fix #2087 
**Checklist:**
> fix: after enable redirect HTTPS, websocket form field disappeared

- .github/workflows/deploy-with-docker.yml
Master push still has errors in https://github.com/apache/apisix-dashboard/runs/3494675500. Related to https://github.com/apache/apisix-dashboard/issues/2108. This PR is going to remove the cache during docker buildx to keep CI passed. Will resolve this in the future.
Fixes https://github.com/apache/apisix-dashboard/issues/2108.
**Checklist:**
> ci: Disable buildx cache to fix CI failure

- api/cmd/stop.go
fix/resolve:
support dashboard run on windows
**Checklist:**
> feat: support Manager API run on windows

- docs/en/latest/FAQ.md
solve the problem of grafana page embedding
fix/resolve #2122 
**Checklist:**
> docs: Update FAQ.md

- .github/workflows/auto-build-rpm.yml
As discussed in #2072, we delay using buildx in `auto-build-rpm` workflow since it relates to the build tool. Now we have updated the build tool(https://github.com/api7/apisix-build-tools/pull/74), it's time to make this change!
fix #2128 
**Checklist:**
> ci: optimize build rpm workflow with apisix-build-tools v2.2.0

- api/conf/schema.json
Fix plugin schema of gzip typo, change `minItem` ot `minItems`. That broken schema will crash frontend page.
fix #2088 
**Checklist:**
> fix: gzip plugin schema typo

- api/build.sh
- api/run.sh
- api/test/docker/setup.sh
Refer to [shellcheck](https://github.com/koalaman/shellcheck) to standardize shell scripting.
example:
```
pwd=`pwd`
```
to:
```
pwd=$(pwd)
```
**Checklist:**
> refactor: lint shell for shellcheck

- web/config/config.ts
This PR sets the default language in apisix-dashboard to en-US.
**Checklist:**
> feat: Setting default language to english in APISIX Dashboard

- api/internal/core/store/storehub.go
Use etcd prefix in plugin_configs template
plugin_configs miss match when the etcd prefix is not '/apisix'
```
2021/11/29 19:40:06 [error] 12464#12464: *21668 [lua] init.lua:400: http_access_phase(): failed to fetch plugin config by id: 383574139283178878, client: 30.49.4.130, server: _, request: "GET /hello HTTP/2.0", host: "xxx.com"
```
```
...
/apisix-3b5e0cc5/upstreams/383566764287460734
{...}
/apisix-3b5e0cc5/upstreams/383570406268732798
{...}
/apisix/plugin_configs/383574139283178878
{...}
...
```
**Checklist:**
> fix: plugin_configs should store with etcd prefix

- web/cypress/integration/route/create-route-with-advanced-matching-conditions.spec.js
- web/src/pages/Route/components/Step1/MatchingRulesView.tsx
- web/src/pages/Route/locales/en-US.ts
- web/src/pages/Route/locales/zh-CN.ts
- web/src/pages/Route/transform.ts
- web/src/pages/Route/typing.d.ts
Support for advanced POST form-based route matching settings introduced in APISIX 2.11. At same time, I also add some tips for advance match.
[https://github.com/apache/apisix/pull/5409](https://github.com/apache/apisix/pull/5409)
**Checklist:**
> feat: support post args advanced match

- web/src/pages/Consumer/components/Step1.tsx
- web/src/pages/Consumer/locales/en-US.ts
- web/src/pages/Consumer/locales/zh-CN.ts
APISIX support consumer name start with number, but APISIX-Dashboard does't support. Does the APISIX-Dashboard need to support consumer that start with number.
And there is the APISIX regex https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L693 
After change:
fix/resolve #2196 
**Checklist:**
> fix(username_regex): cp consumer name regx different with dp

- api/internal/core/server/http.go
- api/internal/core/server/server.go
- api/internal/filter/authentication.go
- api/internal/filter/authentication_test.go
- api/internal/filter/ip_filter_test.go
- api/internal/filter/logging_test.go
- api/internal/handler/upstream/upstream_test.go
- api/internal/route.go
- api/test/e2e/route_import_test.go
- api/test/e2enew/base/base.go
- api/test/e2enew/migrate/migrate_test.go
- api/test/e2enew/stream_route/stream_route_test.go
- api/test/e2enew/upstream/upstream_keepalive_pool.go
- api/test/e2enew/upstream/upstream_test.go
- api/test/testdata/import/multi-routes.yaml
authentication middleware is implemented by changing from framework droplet to framework gin
**Checklist:**
> fix: authentication middleware is implemented by changing from framework droplet to framework gin

- web/src/components/Plugin/PluginDetail.tsx
remove the tip in the key-auth configure page when create/configure route 、 service and global plugin.
resolve #2092 
**Checklist:**
> feat(route): remove key-auth plugin tip

- web/src/components/Upstream/components/active-check/Port.tsx
Remove upstream health check default port.
fix #2186 
**Checklist:**
> chore(upstream): remove default port for upstream health check 

- web/src/locales/en-US/component.ts
- web/src/locales/zh-CN/component.ts
- web/src/pages/Route/List.tsx
- web/src/pages/Route/components/Step1/MetaView.tsx
- web/src/pages/Route/transform.ts
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Display route id at route list and edit views.
fix/resolve #1595
**Checklist:**
> feat(route): show route id in list and edit views.

- api/internal/handler/data_loader/route_import_test.go
fix/resolve #2281
**Checklist:**
> fix: get current dir error

- web/cypress/integration/route/create-edit-duplicate-delete-route.spec.js
- web/src/pages/Route/List.tsx
fix/resolve #2222 
**Checklist:**
add loading status in route page when the Internet is slow
>
> chore: add loading in route page 

- api/internal/core/entity/entity.go
- api/internal/core/entity/format_test.go
- api/test/e2enew/upstream/upstream_retry.go
fix issue https://github.com/apache/apisix-dashboard/issues/2297 by changing retries type int to *int
Change the type of the field `api/internal/core/entity/entity.go:166` retries from int to *int.
[fix/resolve #0001](https://github.com/apache/apisix-dashboard/issues/2297)
**Checklist:**
> fix: retries field to support zero value

- api/internal/core/entity/entity.go
- api/internal/core/entity/format_test.go
- api/test/e2enew/upstream/upstream_keepalive_pool.go
A struct filed will be omit  which have `omitempty` tag and be set to default value, so we should use pointer to avoid this problem.
fix/resolve #2294 
**Checklist:**
> fix: idle_timeout filed to support set zero value

- web/cypress/integration/route/create-route-with-limit-req-form.spec.js
- web/src/components/Plugin/UI/limit-req.tsx
- web/src/components/Plugin/locales/en-US.ts
- web/src/components/Plugin/locales/zh-CN.ts
Add rejected_msg field to limit-req plugin form.
https://github.com/apache/apisix-dashboard/issues/2310
**Checklist:**
> fix: add rejected_msg field to limit-req plugin form

- web/src/pages/Route/List.tsx
Set width for table column and add ellipsis for route table content,If the table content is too long, it will be omitted and displayed in the form of a tooltip.
https://github.com/apache/apisix-dashboard/issues/1992
**Checklist:**
> style: add ellipsis for route table

- web/cypress/integration/route/create-route-with-limit-count-plugin-form.spec.js
- web/src/components/Plugin/UI/limit-count.tsx
- web/src/components/Plugin/locales/en-US.ts
- web/src/components/Plugin/locales/zh-CN.ts
Added group, allow_degradation, show_limit_quota_header fields to the limit-count plugin form.
resolve #2301
**Checklist:**
> feat: Add more fields to limit-count plugin

- web/cypress/integration/route/create-route-with-limit-count-plugin-form.spec.js
- web/src/components/Plugin/UI/limit-count.tsx
- web/src/components/Plugin/locales/en-US.ts
- web/src/components/Plugin/locales/zh-CN.ts
Add rejected_msg field to limit-count plugin form.
fix #2094 
**Checklist:**
> fix: add rejected_msg field to limit-count plugin form

- web/cypress/integration/route/create-route-with-search-service-and-set-priority.spec.js
- web/src/components/Upstream/UpstreamForm.tsx
- web/src/components/Upstream/components/UpstreamSelector.tsx
- web/src/components/Upstream/locales/en-US.ts
- web/src/pages/Upstream/locales/en-US.ts
- web/src/pages/Upstream/locales/zh-CN.ts
When Service is selected in the form in step 1:
The Upstream selector will select "None" by default in the form in step 2:
When Service is not selected in the form in step 1:
resolve #2167 
**Checklist:**
> chore: Create route form optimization

- api/conf/schema.json
- api/internal/handler/schema/plugin_test.go
- api/test/e2enew/schema/schema_test.go
- web/src/components/Plugin/data.tsx
Adapt Apache APISIX version 2.12.1, synchronize schema to support new plugins.
follow: https://github.com/apache/apisix/pull/6254
**Checklist:**
> feat: basic support Apache APISIX 2.12.1

- web/cypress/integration/route/create-route-with-advanced-matching-conditions.spec.js
- web/src/pages/Route/components/Step1/MatchingRulesView.tsx
- web/src/pages/Route/transform.ts
- web/src/pages/Route/typing.d.ts
Correct handling ! (reverse) operator
fix #2166
**Checklist:**
> fix: ! (reverse) operator not handled correctly

- api/internal/handler/data_loader/loader/loader.go
This PR is the basis for the refactored data import functionality, which provides the key `Import`/`Export` interface definition and `DataSets` data interface so that we can implement different data import implementations, such as OpenAPI or Swagger.
This is part of the refactoring, and a refactoring of the OpenAPI codec will be submitted later.
**Checklist:**
> feat: add data loader framework

- api/conf/conf.yaml
- api/internal/conf/conf.go
- api/internal/filter/cors.go
- api/test/shell/cli_test.sh
> feat: add security header

- CHANGELOG.md
Fix the formatting error of CHANGELOG.md; For master
**Checklist:**
> fix: format error in changelog

- api/internal/log/zap.go
- api/test/shell/cli_test.sh
fix/resolve #2365
**Checklist:**
> fix: caller location error in logs

- api/test/e2enew/id_compatible/id_compatible_suite_test.go
- api/test/e2enew/id_compatible/id_crossing_test.go
- api/test/e2enew/id_compatible/id_not_in_body_test.go
- api/test/e2enew/id_compatible/id_using_int_test.go
- api/test/e2enew/id_compatible/id_using_string_test.go
migrate id compatible tests to e2enew
fix/resolve #
**Checklist:**
> refactor: migrate id compatible tests to e2enew

- README.md
> chore: update README for online demo

- api/test/e2enew/route/host_test.go
- api/test/e2enew/route/route_test.go
migrate route tests to e2enew
fix/resolve #
**Checklist:**
> refactor: migrate route tests to e2enew

- api/conf/schema.json
- api/internal/core/store/validate_test.go
- api/internal/handler/schema/plugin_test.go
- api/test/e2enew/consumer/consumer_test.go
- api/test/e2enew/label/label_test.go
- api/test/e2enew/route/route_export_test.go
- api/test/e2enew/route/route_with_plugin_limit_count_test.go
- api/test/e2enew/schema/schema_test.go
- api/test/e2enew/service/service_test.go
- api/test/testdata/invalid-dag-conf.json
- docs/en/latest/IMPORT_OPENAPI_USER_GUIDE.md
- web/cypress/fixtures/plugin-dataset.json
- web/cypress/integration/consumer/create_and_delete_consumer.spec.js
- web/src/components/Plugin/PluginDetail.tsx
- web/src/components/Plugin/UI/cors.tsx
- web/src/components/Plugin/UI/limit-count.tsx
- web/src/components/Plugin/UI/proxy-mirror.tsx
- web/src/components/Plugin/data.tsx
- web/src/components/Plugin/locales/en-US.ts
- web/src/components/Plugin/locales/zh-CN.ts
- web/src/components/Upstream/components/ServiceDiscovery.tsx
- web/src/components/Upstream/locales/en-US.ts
- web/src/components/Upstream/locales/zh-CN.ts
support Apache APISIX 2.13.0
**Checklist:**
> feat: basic support Apache APISIX 2.13.0

- api/internal/core/entity/entity.go
i set  active health check  with https , and filed  `Active.checks.active.https_verify_certificate`  in request body  was true ( bool ).  it return error (json: cannot unmarshal bool into Go struct field Active.checks.active.https_verify_certificate of type string).   it is  filed `Active.checks.active.https_verify_certificate `in golang  that is a string ，different to  filed  `Active.checks.active.https_verify_certificate`  in request.  it  is  , alse ,  different  with   the  one  schema defined in   apisix.
**Checklist:**
> fix: correct data  type of filed Active.checks.active.https_verify_certificate

- docs/en/latest/develop.md
Signed-off-by: Yeming Gu <yeminggood@gmail.com>
Add some tips into `develop.md` to improve comprehensibility.
- advise to change the `make-api` address explicitly. Otherwise, an `403 forbidden` error will be generated when logging in, because the API address cannot be found.
- prompt the user to ignore gyp errors during `yarn install`
fix/resolve #2427 
**Checklist:**
> docs: update some tips in develop.md

- web/cypress/integration/route/can-skip-upstream-when-select-service-id.spec.js
- web/src/pages/Route/components/Step1/MatchingRulesView.tsx
fix/resolve #2438
1.fix matching in the route create page causes the page to crash
**Checklist:**
> fix: advance matching in the route create page causes the page to crash

- api/conf/schema.json
- web/cypress/fixtures/plugin-dataset.json
- web/cypress/integration/consumer/create-consumer-with-api-breaker-plugin-form.spec.js
- web/src/components/Plugin/UI/api-breaker.tsx
- web/src/components/Plugin/locales/en-US.ts
- web/src/components/Plugin/locales/tr-TR.ts
- web/src/components/Plugin/locales/zh-CN.ts
basic support Apache APISIX 2.14.1
**Checklist:**
> feat: basic support Apache APISIX 2.14.1

- api/go.mod
- api/go.sum
- api/internal/handler/data_loader/loader/openapi3/export.go
- api/internal/handler/data_loader/loader/openapi3/import.go
- api/internal/handler/data_loader/loader/openapi3/import_test.go
- api/internal/handler/data_loader/loader/openapi3/openapi3.go
- api/test/testdata/import/Postman-API101.yaml
Improved backend implementation of OpenAPI3 import to enable import of standard OpenAPI3 minimum use cases. In the current PR I will not do the integration work, this separate module will be checked by way of unit tests and in the next PR it will be integrated into the data import interface.
**Checklist:**
> refactor: OpenAPI 3 parse and convert

- api/internal/filter/invalid_request.go
- api/internal/filter/invalid_request_test.go
- api/internal/route.go
- api/test/e2e/middlewares/gzip_test.go
- api/test/e2e/middlewares/invalid_request_test.go
- api/test/e2e/middlewares/middlewares_suite_test.go
The current middleware configuration may cause the caller to check if a file exists on the server by constructing a special URL, so new middleware is added to block requests with unusual characters in the URL.
Please note that this is not a serious problem, the current code prevents arbitrary file reading issues and no one can get access to the files on your server or write to any files.
**Checklist:**
> fix: block arbitrary file index

- web/src/pages/Route/Create.tsx
- web/src/pages/Route/typing.d.ts
Remove ID when copying routes.
fix #2407 
**Checklist:**
> fix: duplicate ID

- .github/workflows/auto-build-rpm.yml
- .github/workflows/backend-cli-test.yml
- .github/workflows/backend-e2e-test.yml
- .github/workflows/backend-unit-test.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy-with-docker.yml
- .github/workflows/frontend-e2e-test.yml
- .github/workflows/frontend-plugin-e2e-test.yml
- .github/workflows/go-lint.yml
- .github/workflows/lint.yml
- .github/workflows/make-build.yaml
- .github/workflows/release-test.yml
- .github/workflows/test-frontend-multiple-node-build.yml
Fix the version of actions used in CI to the latest root version, e.g. v2.1.6 => v3, to reduce the number of PRs in dependbot.
> ci: fix actions version to latest root version

- api/test/shell/cli_test.sh
Fix a burst error in CLI test.
> fix: invalid etcd case in cli test

- api/test/shell/cli_test.sh
Fix a burst error in CLI test.
Same with #2532
> fix: cli test invalid etcd

- api/conf/conf.yaml
- docs/en/latest/USER_GUIDE.md
This PR is primarily intended to address the issue of not displaying embedded Grafana dashboards properly.
The issue can be viewed in this issue #2546 .
This issue is caused by the Dashboard updating the CSP (content security policy) feature. You need to add the appropriate configuration for the Grafana dashboard to display properly. This simply adds the configuration options that have been validated and the corresponding documentation.
This PR can also be referenced by the [APISIX-Docker project](https://github.com/apache/apisix-docker/pull/340).
fix #2546 
**Checklist:**
> doc(csp): add correct csp rule

- web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js
- web/src/components/Plugin/PluginPage.tsx
fix/resolve #2592 
**Checklist:**
> fix: page refresh causes deletion exception

- api/conf/conf.yaml
- api/internal/conf/conf.go
- api/internal/filter/invalid_request.go
- api/internal/handler/data_loader/loader/openapi3/import.go
- api/internal/handler/data_loader/route_import.go
feat: The series PR will add a new feature to the Dashboard to make it support login through OpenID-Connect. 
This PR only adds some new config information to the config file.
fix: Fix some errors occurred in go-lint test
**Checklist:**
> feat: Add config struct of OpenID-Connect Login

- README.md
Add a Slack invitation link badge
**Checklist:**
> docs: add Slack invitation link badge

- Dockerfile
- web/cypress/e2e/rest/pluginTemplate-create-plugin-template-with-route.cy.js
- web/src/pages/Route/transform.ts
- web/yarn.lock
Ensure that the service and plugin templates in the route can be used at the same time.
fix #2648 
**Checklist:**
> fix: plugin_config missing on service exist

- web/cypress/e2e/plugin/plugin-schema.cy.js
- web/cypress/e2e/rest/pluginTemplate-create-edit-delete-plugin-template.cy.js
- web/cypress/e2e/rest/pluginTemplate-create-plugin-template-with-route.cy.js
- web/cypress/e2e/rest/upstream-create_and_edit_upstream_with_no_nodes.cy.js
- web/package.json
- web/yarn.lock
Accoding to this idea ( https://github.com/ant-design/pro-components/issues/1921 ) ,  I upgraded its version.
fix/resolve #2613
**Checklist:**
> fix:ant-table unable to request(#2613)

- .github/workflows/backend-e2e-test.yml
- api/conf/conf.yaml
- api/internal/conf/conf.go
- api/internal/route.go
Add a switch to OIDC authentication to allow users to turn that feature off and turn it off by default.
next #2608 
**Checklist:**
> feat: add enable flag to oidc function

- api/go.mod
- docs/en/latest/install.md
User who install apisix-dashboard from source will know go version need 1.16+
https://github.com/apache/apisix-dashboard/issues/2673#issuecomment-1333524852
because of etcd client v3.5.5 require `io/fs`, then we need upgrade go version to 1.16+
**Checklist:**
> fix: bump go version to 1.16

- web/src/components/Plugin/locales/en-US.ts
- web/src/components/Plugin/locales/tr-TR.ts
- web/src/components/Plugin/locales/zh-CN.ts
On the Cors plugin config page, the allow_origins_by_regex help message is misleading the user.
This PR optimize "allow_origins_by_regex tooltip" description。
fix/resolve #2669
> chore: optimize "allow_origins_by_regex tooltip" description

- web/.eslintrc.js
- web/src/components/Plugin/PluginDetail.tsx
- web/src/components/Plugin/PluginPage.tsx
Reference https://github.com/apache/apisix/issues/7482. In the new version of APISIX, the plugin disabled move to _meta, and the dashboard needs to be changed synchronously.
**Checklist:**
> fix: adapt APISIX plugin disabled

- web/cypress/e2e/plugin/plugin-schema.cy.js
- web/src/components/Plugin/PluginDetail.tsx
fix/resolve https://github.com/apache/apisix-dashboard/issues/2696
**Checklist:**
> fix: plugin configuration lost in editor

- web/src/pages/Route/List.tsx
- web/src/pages/Route/typing.d.ts
1. Add attribute `plugins` to `ResponseBody`
2. Add width attribute to columns of `labels` and `plugins` (Due to without width, these columns might not display  as expected)
3.  Add new render function for `plugins` columns.
fix/resolve #2665 
**Checklist:**
Why not test cases and corresponding document? Cause of it just was a bug fix.
> fix plugins display in list of routes

- web/src/components/Plugin/PluginDetail.tsx
- web/src/components/Plugin/PluginPage.tsx
fix/resolve https://github.com/apache/apisix-dashboard/issues/2732
**Checklist:**
> fix: plugin config page error

- api/internal/handler/schema/plugin.go
- api/test/e2e/route/route_with_plugin_jwt_test.go
I tried to disable the plugin in the configuration plugins content of `conf.yaml` when answering the issue question and it didn't work. After reading the code in the plugin section, I found that in a previously submitted PR https://github.com/apache/apisix-dashboard/pull/1592, the judgment of whether the plugin is enabled or not was removed. So this PR I fixes the problem and support disabling plugins in `conf.yaml` plugins.
fix/resolve #2735
**Checklist:**
> fix: Plugin disable invalid in API /plugin?all=true

- README.md
The previous server is about to expire, so we need to update the URL of the online playground.
**Checklist:**
> fix: update URL of the online playground

- api/internal/core/entity/entity.go
- api/test/e2e/route/route_test.go
fix/resolve #2610 
**Checklist:**
> fix: remove route name length limit

- api/internal/handler/route/route.go
- api/internal/handler/service/service.go
- api/internal/handler/upstream/upstream.go
- web/cypress/e2e/route/search-route.cy.js
- web/src/pages/Route/List.tsx
- web/src/pages/Route/service.ts
- web/src/pages/Service/List.tsx
- web/src/pages/Service/service.ts
- web/src/pages/Upstream/List.tsx
- web/src/pages/Upstream/service.ts
This PR adds search functionality for fields like ID, host, and description. Users can now search for specific entries in the dataset using keywords in these fields.
fix/resolve #2729
**Checklist:**
> Add search functionality for ID, host, and description fields

- web/cypress/e2e/route/create-edit-route-with-redirect-plugin.cy.js
- web/src/pages/Route/Create.tsx
fix/resolve #2445 
**Checklist:**
> fix: remove ssl check in redirect https

- docs/en/latest/modules/data_loader/openapi3.md
- web/cypress/e2e/rest/pluginTemplate-create-edit-delete-plugin-template.cy.js
- web/src/pages/Route/List.tsx
- web/src/pages/Route/service.ts
The export openapi func doesn't work well, we need to disable it for now. This PR disables the frontend section.
refer backend PR: #2801 
**Checklist:**
> feat: disable route's export OpenAPI func

- api/internal/core/entity/entity.go
Apisix and Apisix-seed support configuration of auto-discovery via Nacos with metadata field, which is an object instead of string, thus adding metadata field to discovery_args will cause apisix-dashboard to crash and unable to restart.
Error log message:
ERROR   store/store.go:405      json unmarshal failed: json: cannot unmarshal object into Go struct field Upstream.discovery_args of type string
None.
**Checklist:**
- [] Have you modified the corresponding document?
> fix upstream discovery args metadata field caused crash.

- .github/workflows/deploy-with-docker.yml
- Dockerfile
- docs/en/latest/deploy-with-docker.md
- web/package.json
- web/yarn.lock
- use registry.yarnpkg.com instead of `registry.taobao.com`
- update Dockerfile use copy of local file instead of use `git clone`
- update ci file to remove `APISIX_DASHBOARD_VERSION=master`
fix/resolve https://github.com/apache/apisix-dashboard/issues/2917
**Checklist:**
> fix: dockerfile build failed

- src/components/form-slice/FormPartCredential.tsx
- src/components/form-slice/FormPartGlobalRules.tsx
- src/components/form-slice/FormPartPluginConfig.tsx
- src/components/form-slice/FormSectionGeneral.tsx
- src/routes/consumer_groups/add.tsx
- src/routes/consumer_groups/detail.$id.tsx
- src/routes/consumers/detail.$username/credentials/add.tsx
- src/routes/consumers/detail.$username/credentials/detail.$id.tsx
- src/routes/consumers/detail.$username/index.tsx
- src/routes/global_rules/add.tsx
- src/routes/global_rules/detail.$id.tsx
- src/routes/plugin_configs/add.tsx
- src/routes/plugin_configs/detail.$id.tsx
- src/routes/protos/detail.$id.tsx
- src/routes/routes/detail.$id.tsx
- src/routes/secrets/add.tsx
- src/routes/services/detail.$id.tsx
- src/routes/ssls/detail.$id.tsx
- src/routes/stream_routes/detail.$id.tsx
- src/routes/upstreams/detail.$id.tsx
All detail pages will not be able to edit the ID.
After this modification, `FormSectionGeneral` will have the following behavior:
**Default, Allow edit**
```tsx
<FormSectionGeneral />
```
**Read Only**
```tsx
// When you need to disable editing of id, you only need to set `readOnly`. 
// `created_at`, `updated_at` will be displayed.
<FormSectionGeneral readOnly />
```
> feat: disable editing of IDs while editing

- .github/workflows/e2e.yml
This is part of the https://github.com/apache/apisix/issues/12234
According to [Events that trigger workflows](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch) , this will allow us to trigger the test manually.
**Why**
This is very suitable for manually running a test to ensure that the dashboard can adapt to the latest APISIX, either on the eve of APISIX's release or after the `APISIX:dev` image is updated.
> feat(workflow/e2e): allow `workflow_dispatch` trigger tests

- .github/workflows/e2e.yml
This is part of the https://github.com/apache/apisix/issues/12234.
Depend on: #3109
According to [Events that trigger workflows](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch) , this will allow us to trigger the test in other repositories.
**Why**
I see in https://github.com/apache/echarts/blob/master/.github/workflows/nightly-next.yml that `repository_dispatch` seems to be available in the Apache repositories.
But I haven't found any information about this feature on the ASF-related websites yet.
Because "This event will only …
> feat(workflow/e2e): allow `repository_dispatch` trigger tests

- src/apis/hooks.ts
- src/apis/routes.ts
- src/apis/stream_routes.ts
- src/config/req.ts
- src/routes/routes/index.tsx
- src/routes/services/detail.$id/routes/index.tsx
- src/routes/services/detail.$id/stream_routes/index.tsx
- src/routes/stream_routes/index.tsx
Depend on https://github.com/apache/apisix/pull/12291
According to https://github.com/apache/apisix/pull/12291, we can now filter out all routes/stream_routes that are not for the current service in the service's routes/stream_routes.
This can reduce user confusion.
However, those containing `service_id` in the routes/stream_routes page list cannot be filtered out for now, because the API does not yet support providing multiple `service_id`s or other methods.
**Screenshots**
create one route `test` in services, create one route `test_without_id` with upstream in routes.
> feat(services): filter routes/stream_routes by `service_id`

- src/routes/stream_routes/add.tsx
- src/routes/stream_routes/detail.$id.tsx
Fixed data processing logic for stream_routes-related components to ensure that data can be correctly echoed or submitted.
These problems are found in PR #3113 
When service_id is available, the upstream related fields that rhf automatically populate should be removed.
> fix(stream_routes): rm `upstream` when has `service_id`

- src/routes/stream_routes/index.tsx
Fixed data processing logic for stream_routes-related components to ensure that data can be correctly echoed or submitted.
These problems are found in PR #3113 
Stream routes only support server_addr, server_port.
> fix(stream_routes): show `server_addr`, `server_port` instead of `name`

- e2e/pom/stream_routes.ts
- e2e/tests/stream_routes.show-disabled-error.spec.ts
- src/components/page-slice/stream_routes/ErrorComponent.tsx
- src/config/req.ts
- src/routes/services/detail.$id/stream_routes/add.tsx
- src/routes/services/detail.$id/stream_routes/detail.$routeId.tsx
- src/routes/services/detail.$id/stream_routes/index.tsx
- src/routes/stream_routes/add.tsx
- src/routes/stream_routes/detail.$id.tsx
- src/routes/stream_routes/index.tsx
In the past, when `proxy_mode` was `http`, the `stream_routes` pages would enter the default error page of tanstack router, which was obviously not user-friendly.
This PR provides an Error Component for this situation and applies it to all `stream_routes` related pages.
At the same time, corresponding tests were added to ensure that the handling of this situation is correct.
|OLD|NEW|
|-|-|
|![image](https://github.com/user-attachments/assets/4823da17-2673-4ec7-884c-1eb5eb3e75d5)|![image](https://github.com/user-attachments/assets/c5289fc6-6a36-4098-9a4c-7eab86bdc928)|
> feat(stream_routes): show disabled error

- package.json
- pnpm-lock.yaml
- src/components/Header/SettingModalBtn.tsx
- src/components/page/SettingsModal.tsx
- src/config/req.ts
- src/stores/global.ts
MobX lacks maintenance and is not compatible with react compiler.
I want to replace MobX with a more active library.
First change the simple use case `global store` to use jotai.
> feat(stores/global): use jotai

- src/routes/consumers/detail.$username/credentials/detail.$id.tsx
|OLD|NEW|
|-|-|
|<img width="1511" alt="image" src="https://github.com/user-attachments/assets/4ab5730a-0b19-4d34-a388-900b22cef5ad" />|<img width="1511" alt="image" src="https://github.com/user-attachments/assets/da9d726f-2d73-4593-ba62-90861daa83fa" />|
> fix(credentials/detail): delete btn style

- src/config/i18n.ts
As described in #3140, https://www.i18next.com/principles/fallback#language-fallback provides the functionality of fallback to the default language, which can be configured directly to achieve the function.
|OLD|NEW|
|-|-|
|<img width="350" alt="CleanShot 2025-08-12 at 11 58 49@2x" src="https://github.com/user-attachments/assets/babe3acb-4c71-4067-a78f-10b6b60b0cdb" />|<img width="350" alt="image" src="https://github.com/user-attachments/assets/3cb2e5e2-0620-4867-b226-9f85d41f07c3" />|
Now, untranslated text will use the en text, while translated text will use the corresponding language's i18n.
example:
```json5
// …
```
> feat(i18n): fallback to en when i18n is incomplete

- e2e/pom/ssls.ts
- e2e/tests/ssls.check-labels.spec.ts
- e2e/utils/ui/labels.ts
- e2e/utils/ui/ssls.ts
- src/apis/ssls.ts
- src/components/form-slice/FormSection/index.tsx
- src/components/form/Editor.tsx
- src/components/form/Labels.tsx
The original code only updated data when it was first mounted, and the timing of resetting form data was uncertain, which often led to rendering failures.
```ts
// The method of applying API data in the detail/edit page
useEffect(() => {
if (sslData && !isLoading) {
form.reset(produceToSSLForm(sslData));
}
}, [sslData, form, isLoading]);
```
Now, it's directly changed to `useMemo`, and the original `useListState` used for data maintenance has been removed, simplifying data maintenance and ensuring that data can be updated correctly.
For the testing part, it has not yet been decided whether to add unit tests, so I've …
> fix(FormItem): Labels

- src/components/form/Editor.tsx
- src/utils/monaco.ts
- vite.config.ts
Ensure that only the bundled Monaco is used.
|OLD|NEW|
|-|-|
|<img width="821" height="400" alt="image" src="https://github.com/user-attachments/assets/ac63ba31-0720-4186-ba6b-873bf1187b7f" /><img width="498" height="514" alt="image" src="https://github.com/user-attachments/assets/39c814f3-d831-414d-ad03-a8459dee3d07" />|<img width="400" height="498" alt="image" src="https://github.com/user-attachments/assets/aedc15e7-e94a-45ec-ba19-56895beee654" /><img width="400" height="498" alt="image" src="https://github.com/user-attachments/assets/b51bcac9-9f66-45b5-8eba-bf0e603b99a9" /><img width="534" height="390" alt="image" …
> fix(form/Editor): only use the bundled monaco editor
