apache/apisix-dashboard

.travis.yml
src/utils/request.ts
src/views/schema/consumers/edit.vue
src/views/schema/consumers/list.vue
src/views/schema/routes/edit.vue
src/views/schema/routes/list.vue
src/views/schema/service/edit.vue
src/views/schema/service/list.vue
src/views/schema/upstream/edit.vue
src/views/schema/upstream/list.vue

Waiting for the latest API to be deployed.

WIP: add desc

---

src/views/schema/consumers/edit.vue
src/views/schema/consumers/list.vue
src/views/schema/routes/edit.vue
src/views/schema/routes/list.vue
src/views/schema/service/edit.vue
src/views/schema/service/list.vue
src/views/schema/ssl/edit.vue
src/views/schema/ssl/list.vue
src/views/schema/upstream/edit.vue
src/views/schema/upstream/list.vue

close https://github.com/iresty/apisix_dashboard/issues/22
close https://github.com/iresty/apisix_dashboard/issues/18
close https://github.com/iresty/apisix_dashboard/issues/21
close https://github.com/iresty/apisix_dashboard/issues/20

WIP: update styles

---

src/components/PluginDialog/index.vue
src/lang/en.ts
src/lang/zh.ts

resolve https://github.com/apache/incubator-apisix/issues/679

Fix plugin has oneOf prop

---

src/views/schema/upstream/edit.vue

fix: https://github.com/apache/incubator-apisix-dashboard/issues/64

enhance: can choose chash keys from drop down list

---

src/views/schema/routes/edit.vue
src/views/schema/routes/list.vue
src/views/schema/service/list.vue
src/views/schema/ssl/list.vue
src/views/schema/upstream/list.vue

1、when enter the router list ,the Action column fixed to the right and always inside view.
2、keep router upstream service list ordered by ID, which I think the ID is generated by ETCD,so it should be like ordered by created date desc, it will be helpful when routers or upstreams are more then 10,
3、support multi hosts and multi uris when create a router，which need APISIX lua be updated which my next PR，when current `schema_def.lua` is not support uris
fix: https://github.com/apache/incubator-apisix-dashboard/issues/59
fix: https://github.com/apache/incubator-apisix-dashboard/issues/58
fix: https://github.com/apache/incubator-apisix-dashboard/issues/57

fix: add new features and function enhance

---

src/components/PluginDialog/index.vue

fix: https://github.com/apache/incubator-apisix-dashboard/issues/71

fix: enable to open websocket

---

src/views/schema/routes/edit.vue

fix: https://github.com/apache/incubator-apisix-dashboard/issues/69

fix:add regexp for uris and host filter when create route

---

src/views/schema/routes/edit.vue

fix: https://github.com/apache/incubator-apisix-dashboard/issues/74

fix configuration not show in route edit page when route uri and host from old format

---

src/views/schema/upstream/edit.vue

fix https://github.com/apache/incubator-apisix/issues/891

set default weight value

---

src/views/schema/ssl/edit.vue
src/views/schema/upstream/edit.vue
src/views/schema/upstream/list.vue

resolve https://github.com/apache/incubator-apisix-dashboard/issues/79
resolve https://github.com/apache/incubator-apisix/issues/898
resolve https://github.com/apache/incubator-apisix/issues/897

Fix some issues 

---

src/layout/components/Sidebar/SidebarLogo.vue

resolve https://github.com/apache/incubator-apisix/issues/939

Fix Favicon doesn't show in history mode

---

src/lang/en.ts
src/lang/zh.ts
src/views/schema/routes/edit.vue

resolve https://github.com/apache/incubator-apisix-dashboard/issues/89

feat: use more semantic tip for edit route

---

src/components/PluginDialog/index.vue

resolve https://github.com/apache/incubator-apisix-dashboard/issues/98

fix: check initial plugin data

---

src/layout/components/Sidebar/SidebarLogo.vue

related PR https://github.com/apache/incubator-apisix-dashboard/pull/110

fix: icon disappear in hash mode

---

src/components/Hamburger/index.vue

#132 
How it looks like 
https://drive.google.com/file/d/1kPXO1ZosTVl_hZOH0wfXvqM104vrtwg7/view?usp=sharing

add inbuilt hamburger icon.

---

config/config.ts
src/utils/request.ts

Adding api key for the request

---

config/config.ts
package.json
src/components/PluginForm/index.tsx
src/components/PluginModal/index.tsx
src/locales/en-US/component.ts
src/locales/zh-CN/component.ts
src/services/plugin.ts
src/transforms/global.ts
src/transforms/plugin.ts
src/typings.d.ts

feat: added Plugin typings

---

src/components/PluginDialog/index.vue

add feature #168 
> Make object properties available for graphical editing
> 图形化编辑对象属性

feature: add object property editor

---

src/locales/en-US/settings.ts
src/locales/zh-CN/settings.ts
src/pages/Settings.tsx
src/typings.d.ts
src/utils/request.ts
src/utils/setting.ts
src/utils/utils.ts

add new setting items with i18n content for AdminAPIConfig

feature: add new setting items with i18n content

---

config/config.ts
netlify.toml

Fix static files url

---

src/pages/SSLModule/create/components/CertificateUploader/index.tsx

update SSL page

---

config/config.ts
config/routes.ts
src/app.tsx
src/pages/ssl/List.tsx
src/pages/ssl/service.ts
src/pages/ssl/typing.d.ts
src/services/user.ts
src/typings.d.ts
src/utils/setting.ts

change request prefix for different environment

feature: change request prefix

---

src/components/PluginForm/READMD.md
src/components/PluginForm/data.ts
src/components/PluginForm/index.ts
src/components/PluginForm/locales/en-US.ts
src/components/PluginForm/locales/zh-CN.ts
src/components/PluginForm/service.ts
src/components/PluginForm/typing.d.ts
src/locales/en-US.ts
src/locales/en-US/menu.ts
src/locales/zh-CN.ts
src/pages/Routes/Create.less
src/pages/Routes/Create.tsx
src/pages/Routes/components/CreateStep3/CreateStep3.tsx
src/pages/Routes/components/CreateStep3/PluginCard.tsx
src/pages/Routes/components/CreateStep3/PluginDrawer.tsx

Feat route

---

src/pages/Routes/Create.tsx
src/pages/Routes/components/CreateStep3/CreateStep3.tsx
src/pages/Routes/components/CreateStep3/PluginDrawer.tsx

feat: update Plugin

---

src/components/PluginForm/PluginForm.tsx
src/components/PluginForm/typing.d.ts
src/global.less
src/pages/Routes/components/CreateStep3/CreateStep3.tsx
src/pages/Routes/components/CreateStep3/PluginDrawer.tsx

Feat step3

---

compose/docker-compose.yml

modify apisix image in compose

modify apisix image in compose

---

api/service/route.go

modify apisix image in composefix upstrampath is nil

fix upstrampath is nil

---

src/pages/Routes/components/Step1/RequestConfigView.tsx
src/pages/Routes/constants.ts
src/pages/Routes/transform.ts
src/pages/Routes/typing.d.ts

add: route priority

---

src/components/PluginDialog/index.vue

* Fix the error can't read property of null when edit an array property. 
* Add a remove button that could remove item from array property.

fix: array property editor

---

package.json
src/layout/components/Sidebar/SidebarLogo.vue
src/store/modules/user.ts
src/utils/request.ts
src/views/login/index.vue

1. Changing logo url path depends on node environment. This should avoid logo missing in production environment.
1. Little changes on login and logout behaviour.

fix logo missing problem

---

src/views/schema/routes/edit.vue

Now the add plug-in option is available for searching

---

compose/docker-compose.yml

fix #294 
A little change to fix etcd container running in Non-Root mode.

fix: etcd cannot start

---

.github/commit-convention.md
package.json
scripts/verifyCommit.js

Add a commit-msg checker
Resolves https://github.com/apache/incubator-apisix-dashboard/issues/140
@juzhiyuan Can you test this on Mac?

Add a commit-msg checker

---

Dockerfile

Fixes #315 .
This PR is going to add Python installation in image for building dashboard.

fix(Deploy): add Python installation in dockerfile

---

src/pages/SSL/Create.tsx
src/pages/SSL/List.tsx
src/pages/SSL/components/CertificateForm/index.tsx
src/pages/SSL/components/CertificateUploader/index.tsx
src/pages/SSL/components/Step1/index.tsx
src/pages/SSL/locales/en-US.ts
src/pages/SSL/locales/zh-CN.ts

feat(i18n): ssl module

---

src/pages/Setting/Setting.tsx
src/pages/Setting/locales/en-US.ts
src/pages/Setting/locales/zh-CN.ts

feat(i18n): set module

---

src/pages/Route/Create.tsx
src/pages/Route/constants.ts

feat(i18n): route module

---

src/components/ActionBar/ActionBar.tsx
src/components/ActionBar/index.ts
src/components/ActionBar/locales/en-US.ts
src/components/ActionBar/locales/zh-CN.ts
src/locales/en-US.ts
src/locales/zh-CN.ts

feat(i18n): actionbar component

---

src/pages/Route/components/Step1/MatchingRulesView.tsx
src/pages/Route/components/Step1/RequestConfigView.tsx
src/pages/Route/transform.ts
src/pages/Route/typing.d.ts

- fix: MatchingRules wrong  unequal value
- fix: transform vars error
#341

fix: transform vars error

---

compose/gen-config-yaml.sh

the previous shell code is not compatible for Macos system, while the `sed` has some difference between different platform.
so I change it in more friendly for macox

feature: support run in mac system

---

src/pages/Consumer/Create.tsx
src/pages/Consumer/List.tsx
src/pages/Route/List.tsx
src/pages/SSL/Create.tsx
src/pages/Upstream/Create.tsx
src/pages/Upstream/List.tsx

feat: combine import

---

src/components/ActionBar/ActionBar.tsx
src/components/ActionBar/locales/en-US.ts
src/components/ActionBar/locales/zh-CN.ts
src/locales/en-US/component.ts
src/locales/zh-CN/component.ts
src/pages/Setting/Setting.tsx
src/pages/Setting/locales/en-US.ts
src/pages/Setting/locales/zh-CN.ts

this pr is changing some i18n according to https://github.com/apache/apisix-dashboard/issues/331 Proposal

feat(i18n): modify some i18n according to the proposal#331

---

README.md
compose/README.md
compose/gen-config-yaml.sh
src/components/Footer/index.tsx
src/components/PluginPage/PluginPage.tsx
src/components/RightContent/index.tsx

doc: remove all ‘incubator’

---

src/locales/en-US.ts
src/locales/zh-CN.ts
src/pages/Consumer/index.ts
src/pages/Route/index.ts

___
- Description
- How to fix?
___
https://github.com/apache/apisix-dashboard/issues/332: locales under src/pages can auto loaded, so this pr removes page locales references.

feat(i18n): Use auto load i18n (#332)

---

.github/workflows/ci.yml

Add a build test by GitHub Actions
For the preview, see https://github.com/Rapiz1/incubator-apisix-dashboard/pull/1/checks?check_run_id=970798716

ci: Add build test

---

README.md

package download timeout in build manager-api.
___
- Description
update deploy doc.
- How to fix?
use go module proxy [Goproxy 中国](https://goproxy.cn/)

update go module proxy

---

compose/gen-config-yaml.sh

___
- Description
- How to fix?
___

fix: mv config.yml to config-default.yml in the latest version of apisix

---

compose/gen-config-yaml.sh

___
- Description
- How to fix?
___

fix #386 wget special output file use -O

---

api/conf/conf_preview.json

___
- Description
- How to fix?
___

fix: preview mysql pwd was wrong

---

src/pages/User/Login.less
src/pages/User/Login.tsx

___
- Description
change copyright footer
- How to fix?
___

fix(authentication): change Apache APISIX copyright

---

api/main.go
api/run/run.sh

___
- Description
fix:  we need conf.json when deploying manager-api in local 
fix: log error when starting manager failed
- How to fix?
___

fix:  we need conf.json when deploying manager-api in local 

---

src/pages/SSL/Create.tsx

**fix issue #406** 
___
- Description
- How to fix?
add a case to handle step =1 
___

fix: click create ssl prestep not response

---

src/pages/Setting/Setting.tsx

fix issue:  #412 
___
- Description
- How to fix?
send request after form validateFields 
___

fix: submit setting grafanaURl without validation

---

api/filter/authentication.go
api/route/authentication.go
api/route/authentication_test.go
compose/dashboard_conf/nginx.conf
src/pages/User/components/LoginMethodPassword.tsx

___
- Description
Modifying the login URL to achieve the compatibility of nginx forwarding.
Modification involves Manager API and front end.
- How to fix?
Change login URL to `/apisix/admin/user/login` from `/user/login` , add an prefix.
___

fix(authentication): change login api url

---

src/components/ActionBar/ActionBar.tsx
src/pages/Route/Create.tsx

fix issue: #418 
___
- Description
- How to fix?
condition to show acttionbar 
___

fix: ActionBar should not appear in create/edit route resultview

---

compose/docker-compose.yml

#416
___
- Description
#416
- How to fix?
fix the mount path
___

fix: after update master, login return error again #416

---

.github/workflows/api_ci.yml
.github/workflows/api_cicd.yml
api/Dockerfile

change: update `dag-to-lua` lib to version 1.1

---

api/service/route.go
api/service/upstream_test.go

___
upstream and route support `chash` and `checks`

feat: upstream and route support `chash` and `checks`

---

.github/workflows/multiple-node-build.yml

Added multiple node builds action

feat: added multiple node builds action

---

.github/workflows/multiple-node-build.yml
README.md
README.zh-CN.md

___
Keep the same as https://github.com/ant-design/ant-design-pro

feat: update README

---

src/pages/Route/Create.tsx

fix issue: #435 
___
- Description
- How to fix?
___

fix: httpheaderrewrite data lost when view update in create route step2

---

api/route/upstream.go

___
- Description
- How to fix?
___
Add paging to the listUpstreamName, and it will get all data without page or size parameters

enhancement: add paging to the listUpstreamName

---

package.json
src/pages/Consumer/Create.tsx
src/pages/Route/Create.tsx
src/pages/Upstream/Create.tsx

resolve #425 
___
Update Consumer's auth-plugin checker policy.

feat(Consumer): update auth plugin check policy

---

api/errno/error.go
api/route/base.go
api/route/route.go
api/route/route_group.go
api/route/route_group_test.go
api/script/db/schema.sql
api/service/route.go
api/service/route_group.go

fix issue: #431 
___
- Description
- How to fix?
___
- add a new module routeGroup: 
-  create table `route_group`
- support CRUD and list route group
- create/update route support add attribute route group id

Feat: manage api  support route group

---

src/pages/Route/Create.tsx
src/pages/Route/components/CreateStep4/CreateStep4.tsx
src/pages/Route/components/Step3/index.tsx

___
- Description
- How to fix?
___
added pluginchart preview in route step4

feat: preview pluginchart

---

.actions/ASF-Release.cfg
.github/workflows/api_ci.yml
compose/dashboard_conf/nginx.conf
docker/nginx.conf

___
- Description
- How to fix?
___
Increase the checking of .conf and .toml files. And delete the redundant configuration of the ASF-Release.cfg file.

Increase the checking of .conf and .toml files. And delete the redundant configuration of the ASF-Release.cfg file.

---

.github/workflows/multiple-node-build.yml

___
Now CI will run lint on all js and style files.
FYI: @juzhiyuan

ci: Add lint

---

src/pages/Route/components/Step1/RequestConfigView.tsx

___
- Description
related issue:  #458 
- How to fix?
___

fix: host should not be required

---

api/internal/core/entity/entity.go

chore: add structs

---

api/route/route.go
api/service/route.go
config/routes.ts
package.json
src/pages/Route/Debug.tsx
src/pages/Route/List.tsx
src/pages/Route/locales/en-US.ts
src/pages/Route/locales/zh-CN.ts
src/pages/Route/service.ts
src/pages/Route/transform.ts
src/pages/Route/typing.d.ts
yarn.lock

fix #469 
___
- Description
- How to fix?
___

feat: Route debug

---

api/internal/handler/consumer/consumer.go
api/route/base.go

feat: add consumer CURD refactoring

---

api/internal/core/entity/entity.go
api/internal/handler/route/route.go
api/internal/handler/ssl/ssl.go
api/route/base.go

feat: add SSL refactoring

---

src/pages/Route/List.tsx
src/pages/Route/transform.ts

___
- Description
- How to fix?
___

feat:  deleting hosts when hosts is empty

---

api/route/route.go

fix: #499 
___
- Description
- How to fix?
get the `BaseUrl` without `:port` case the error. updated to match this case.
___

fix: get debuginfo return 500 in online demo site

---

api/route/route.go
api/route/route_test.go

fix: #499 
___
- Description
- How to fix?
upate regexp for get apisix url from Baseurl
___

fix: regexp for apisix url in get debuginfo api

---

api/internal/core/entity/entity.go
api/internal/core/storage/etcd.go
api/internal/core/storage/storage.go
api/internal/core/store/store.go
api/internal/core/store/store_test.go
api/internal/core/store/validate.go
api/internal/core/store/validate_test.go
api/internal/handler/consumer/consumer.go
api/internal/handler/handler.go
api/internal/handler/route/route.go
api/internal/handler/service/service.go
api/internal/handler/ssl/ssl.go
api/internal/handler/upstream/upstream.go
api/internal/utils/closer.go
api/internal/utils/consts/error.go
api/route/base.go

add Service and Upstream refactoring

feat: add Service and Upstream refactoring

---

api/build.sh
api/conf/conf.go
api/conf/conf.json
api/conf/conf_preview.json
api/route/route.go
api/run/run.sh
api/service/consumer.go
compose/manager_conf/build.sh
src/pages/Route/transform.ts

fix: #499 
___
- Description
- How to fix?
Add a config item APISIX_DEBUG_URL, which should be configed the accessible apisix address 
___

fix: add a config item APISIX_DEBUG_URL to support online debug

---

package.json
yarn.lock

#490 
___
- Description
- How to fix?
___
added plugin category

feat: update pluginchart version(1.0.13)

---

src/pages/Consumer/locales/en-US.ts
src/pages/Consumer/locales/zh-CN.ts
src/pages/Route/List.tsx
src/pages/Route/components/Step1/RequestConfigView.tsx
src/pages/Route/locales/en-US.ts
src/pages/Route/locales/zh-CN.ts

fix: #524 
___
- Description
- How to fix?
___

fix(i18n): update error key in requestConfigView.tsx

---

src/pages/Consumer/List.tsx
src/pages/Consumer/service.ts
src/pages/Route/service.ts

___
- Description
- How to fix?
___

feat: refactor consumer

---

api/internal/handler/consumer/consumer.go
api/internal/handler/consumer/consumer_test.go
api/internal/handler/route/route.go
api/internal/handler/route/route_test.go
api/internal/handler/service/service.go
api/internal/handler/service/service_test.go
api/internal/handler/ssl/ssl.go
api/internal/handler/ssl/ssl_test.go
api/internal/handler/upstream/upstream.go

___
support search for resource list

feat: support search for resource list

---

api/build-tools/schema-sync.lua
api/internal/core/entity/entity.go
api/internal/core/entity/format.go
api/internal/core/entity/format_test.go
api/internal/core/store/store.go
api/internal/core/store/store_test.go
api/internal/handler/consumer/consumer.go
api/internal/handler/consumer/consumer_test.go
api/internal/handler/route/route.go
api/internal/handler/route/route_test.go
api/internal/handler/service/service.go
api/internal/handler/ssl/ssl.go
api/internal/handler/upstream/upstream.go

___
compatible with PUT method of `admin api` and nodes of upstream

feat: compatible with PUT method of `admin api` and nodes of upstream

---

src/pages/Route/components/Step1/RequestConfigView.tsx

___
- Description
as title
- How to fix?
___

fix: lose focus when input in route step1

---

api/internal/core/store/validate.go
api/internal/core/store/validate_test.go
api/internal/handler/handler.go
api/internal/handler/route/route_test.go
api/internal/utils/consts/api_error.go

fix: add custom checking for resource's conf

---

src/pages/Upstream/List.tsx

___
- Description
as title
- How to fix?
___

fix(Upstream): list item desc not showing

---

src/helpers.tsx
src/locales/en-US/component.ts
src/locales/zh-CN/component.ts
src/pages/SSL/Create.tsx
src/pages/SSL/List.tsx
src/pages/SSL/components/CertificateForm/index.tsx
src/pages/SSL/locales/en-US.ts
src/pages/SSL/locales/zh-CN.ts
src/pages/SSL/service.ts
src/pages/SSL/typing.d.ts

resolve https://github.com/apache/apisix-dashboard/issues/585

feat(SSL): added SSL

---

api/build-tools/schema-sync.sh
api/build.sh
docs/deploy.md
docs/deploy.zh-CN.md
docs/develop.md
docs/develop.zh-CN.md

feat: separate build and run to 2 scripts

---

README.md
README.zh-CN.md

___
- Add etcd api version tips
___
resolve #602

doc: add etcd api version tips

---

api/conf/conf.go

___
using relative path to read conf and json schema

fix: using relative path to read conf

---

frontend/src/pages/Route/transform.ts

___
- Description
Put incorrect Prometheus value when update route. 
resolved #627 
- How to fix?
___

fix: promethus incorrect value when update route

---

.github/workflows/frontend-e2e-test.yml

___
- Description
- How to fix?
___
As title.

feat: cache Front-end e2e CI node_modules

---

api/internal/handler/route/route.go
api/internal/handler/route/route_test.go
api/internal/route.go

- fix issues
fix #695
fix #690

fix:bug that dirty data exists after updating route and wrong mod for prod env

---

web/src/components/Upstream/UpstreamForm.tsx

feat(Upstream): update active check's field order

---

web/src/components/Upstream/UpstreamForm.tsx
web/src/pages/Route/components/Step1/MatchingRulesView.tsx

fix: minor issues

---

api/conf/schema.json

regenerate `jsonschema` and format

chore: update jsonschema

---

api/Dockerfile-for-test
api/test/docker/Dockerfile
api/test/docker/docker-compose.yaml

move `api/Dockerfile` into `api/test/docker`

chore: move the Dockerfile that may be confusing

---

web/src/pages/Route/List.tsx
web/src/pages/Route/transform.ts
web/src/pages/Route/typing.d.ts

related issue https://github.com/apache/apisix-dashboard/issues/717
related comments 
- https://github.com/apache/apisix-dashboard/issues/717#issuecomment-723812310
- https://github.com/apache/apisix-dashboard/issues/717#issuecomment-723938292

feat: convert uri to uris

---

Makefile

___
- Description
the path of /web error
- How to fix?
___

fix: make build error

---

CHANGELOG.md
CHANGELOG.zh-CN.md

___
- Description
- How to fix?
___
As title.

feat: update changelog

---

api/conf/schema.json
api/internal/core/entity/entity.go
api/internal/core/store/validate.go
api/internal/handler/route/route_test.go
api/internal/handler/service/service_test.go
api/internal/handler/upstream/upstream_test.go

sync json schema of APISIX master branch to support consumer schema for auth plugin
close #665

fix: consumer schema for auth plugin

---

docs/deploy.md
docs/deploy.zh-CN.md
docs/develop.md
docs/develop.zh-CN.md
docs/examples/docker-conf-example.yaml

fix: doc typo

---

docs/develop.md
docs/develop.zh-CN.md

fix develop doc for sync json schema

fix: develop doc for sync json schema

---

api/internal/core/storage/etcd.go

fix https://github.com/apache/apisix-dashboard/issues/779

fix: closed WatchResponse channel when cancel function is called (#779)

---

api/test/shell/cli_test.sh

fix CI fail, according `api/conf/conf.yaml` changed in PR #785

fix: make cli test more compatible

---

api/test/e2e/base.go
api/test/e2e/upstream_test.go

test: fix e2e test unstable

---

Makefile
docs/deploy.md
docs/deploy.zh-CN.md

___
- Description
- How to fix?
___

feat(Makefile): update release-src

---

.github/workflows/backend-unit-test.yml

ci: fix CI fail

---

api/conf/schema.json

sync json schema from APISIX master branch

chore: sync json schema from APISIX

---

CHANGELOG.md
CHANGELOG.zh-CN.md

___
- Description
- How to fix?
___
update 2.1 changelog

feat: update 2.1 changelog

---

docs/deploy.md
docs/deploy.zh-CN.md

feat(docs): update deploy

---

api/test/e2e/route_service_upstream_test.go

The polling order is not fixed, causing CI to fail sometimes:
https://github.com/apache/apisix-dashboard/pull/864/checks?check_run_id=1447899335#step:5:142
updated refer to:
https://github.com/apache/apisix/blob/master/t/node/rr-balance.t#L149-L176

fix: test cases for upstream nodes roundrobin

---

api/test/docker/Dockerfile-apisix
api/test/docker/apisix_config.yaml
api/test/docker/docker-compose.yaml

use APISIX master branch code to run e2e test.

ci: use APISIX master branch code to run e2e test

---

README.md

docs: currently considered experimental.

---

api/conf/schema.json
api/internal/core/store/validate_test.go

sync json schema that sort key
close:  #877

chore: sync json schema

---

api/test/e2e/base.go
api/test/e2e/consumer_test.go

https://github.com/apache/apisix-dashboard/issues/607
___
- Description
- How to fix?
___

test: add consumer with key-auth ( E2E )

---

api/test/e2e/base.go
api/test/e2e/route_with_auth_plugin_test.go

test: add e2e test cases for route with auth plugin

---

api/test/e2e/route_with_limit_plugin_test.go

test: add e2e test cases for route with limit plugin

---

web/src/pages/Route/components/Step1/RequestConfigView.tsx
web/src/pages/Route/constants.ts
web/src/pages/Route/locales/en-US.ts
web/src/pages/Route/locales/zh-CN.ts
web/src/pages/Route/transform.ts
web/src/pages/Route/typing.d.ts

resolves #855 
___
- Description
- How to fix?
___

feat: add remote_addrs in route step1 page

---

api/test/e2e/base.go
api/test/e2e/route_with_other_plugin_test.go
api/test/e2e/route_with_plugin_proxy_rewrite_test.go

test: add e2e test cases for route with plugin `proxy-rewrite`

---

api/test/docker/apisix_config.yaml
api/test/docker/docker-compose.yaml
api/test/e2e/route_with_log_plugin_test.go
api/test/e2e/route_with_valid_remote_addr_test.go

test: add e2e test cases for route with log plugin

---

.github/workflows/backend-cli-test.yml
api/build-tools/schema-sync.lua
api/build-tools/schema-sync.sh
api/test/shell/cli_test.sh

fix: bug for build tool `schem-sync`

---

.github/workflows/backend-cli-test.yml

close #916
remove schema sync test from CI
we just make sure it can run with corresponding APISIX version

fix: remove schema sync test from CI

---

api/test/e2e/route_with_metric_plugin_test.go

test: add e2e test cases for route with metric plugin

---

api/test/e2e/route_with_management fileds_test.go

test: add e2e test cases for route wit management fileds

---

api/internal/core/entity/format.go
api/internal/core/entity/format_test.go

fix: upstream node can't display when the node's weight is set to 0

---

api/test/docker/docker-compose.yaml

ci: run the E2E test cases with APISIX 2.1

---

.github/workflows/deploy-with-docker.yml
docs/deploy-with-docker.md
docs/deploy-with-docker.zh-CN.md

Fix #920 
should deploy code in master branch to the online demo

CD: auto deploy codes on the master branch to the online demo

---

api/test/e2e/route_with_management_fileds_test.go

test: config route with management fileds (E2E)

---

api/test/e2e/consumer_test.go

test: fix the problem that consumer test cases cause CI failure (E2E)

---

web/package.json
web/src/pages/Route/transform.ts
web/yarn.lock

fix https://github.com/apache/apisix-dashboard/issues/956

fix: use correct method to get object's length

---

api/conf/conf.yaml

fix https://github.com/apache/apisix-dashboard/issues/967
___
- Description
- How to fix?
___

feat: aligned comments conf.yaml

---

api/test/e2e/balancer_test.go

resolve https://github.com/apache/apisix-dashboard/issues/988

test: e2e test balancer (roundrobin upstream)

---

api/test/e2e/upstream_chash_hash_on_test.go

resolved https://github.com/apache/apisix-dashboard/issues/993

test: e2e test chash upstream with key (wrong key, vars)

---

.github/workflows/markdown-link-checker.yml

feat(CI): supoort markdown links checker

---

docs/USER_GUIDE.md
docs/USER_GUIDE.zh-CN.md

Optimized docs to add Metrics page Gragana configuration guide

docs: optimize metrics document

---

README.md
README.zh-CN.md

docs: update README's style

---

api/internal/handler/consumer/consumer.go
api/internal/handler/consumer/consumer_test.go
api/test/e2e/consumer_test.go

fix: delete POST method in /apisix/admin/consumer

---

.github/workflows/gitleaks.yml

None
Support [gitleaks](https://github.com/zricethezav/gitleaks) to scan hardcoded password.
refer to https://github.com/ant-design/ant-design/blob/master/.github/workflows/gitleaks.yml

ci: support gitleaks to scan hardcoded password

---

.github/workflows/release-test.yml

___
- Description
release test run failed sometimes
- How to fix?
sleep seconds to make sure Manager API is up.

ci: fix release test run failed

---

web/config/proxy.ts
web/src/components/Plugin/PluginPage.tsx

fix(plugin): set disable but useless

---

README.md

docs: update README to remind that the master version should work with APISIX master version

---

api/internal/handler/server_info/server_info.go
api/test/e2e/server_info_test.go

feat: put server_info under the admin api

---

web/cypress/integration/route/create-and-delete-route.spec.js

___
- Description
- How to fix?
___

feat(FE): update route e2e

---

web/src/components/Upstream/UpstreamForm.tsx
web/src/pages/Upstream/locales/en-US.ts
web/src/pages/Upstream/locales/zh-CN.ts
web/src/pages/Upstream/transform.ts
web/src/pages/Upstream/typing.d.ts

feat: active check support custom port

---

web/src/global.less

feat: support line break

---

.github/workflows/backend-unit-test.yml
Dockerfile
api/go.mod
api/go.sum
api/internal/handler/route/route.go
api/test/docker/Dockerfile
docs/deploy.md

close #618 
___
use Lua VM and compiler written in Go, so that we don't need to install Lua separately

chore: remove Lua dependency

---

web/src/pages/Route/components/Step1/RequestConfigView.tsx
web/src/pages/Route/transform.ts
web/src/pages/Route/typing.d.ts

feat: added websocket tab for route

---

web/src/pages/Route/components/DebugViews/DebugDrawView.tsx
web/src/pages/Route/constants.ts

part of #1077 
___
- How to fix?
1. add protocol select to avoid input wrong protocol
2. fix bug when clear all params

fix: add protocol select

---

web/src/pages/Route/components/DebugViews/DebugDrawView.tsx

fix(FE): misspelling

---

api/conf/schema.json
api/internal/core/store/validate.go
api/internal/core/store/validate_test.go
api/internal/handler/plugin/plugin.go
api/internal/handler/plugin/plugin_test.go

close #532
close #605
close #990
___
provides an API to get plugin's name, priority, schema, consumer_schema and version.
all plugins are applicable, including custom plugins.

feat: provide the ability to view plugin type and other properties

---

api/test/e2e/route_test.go

issue has resolved by https://github.com/apache/apisix/pull/3008
just add e2e test cases for it
close #984

feat: add test cases for rejecting request data if it contains an empty array

---

.github/workflows/spellchecker.yml

feat: add spell checker (#1013)

---

api/internal/handler/consumer/consumer.go
api/internal/handler/consumer/consumer_test.go
api/test/e2e/consumer_test.go
api/test/e2e/route_online_debug_test.go
api/test/shell/cli_test.sh
web/src/pages/Consumer/service.ts

fix: delete POST method in /apisix/admin/consumer 

---

web/src/components/Upstream/UpstreamForm.tsx
web/src/pages/Route/typing.d.ts

feat: support EWMA

---

web/src/components/Footer/index.tsx

1. Change from 2020 to 2021 in the footer

docs: 2020 update to 2021

---

web/cypress/integration/upstream/create_and_delete_upstream.spec.js

feat(FE): improve upstream e2e testcase

---

web/src/locales/zh-CN/menu.ts
web/src/pages/Consumer/locales/en-US.ts
web/src/pages/Consumer/locales/zh-CN.ts

As the preparation for release v2.3, this PR is going to cherry-pick 50bcbe9 from master branch to v2.3 branch. Regarding to the details, please refer to #1212  .

feat: Improve consumer for i18n (#1212)(backport to v2.3)

---

CHANGELOG.md

___
- Description
- How to fix?
___

doc: add changelog for v2.3

---

.github/PULL_REQUEST_TEMPLATE

___
Since the PRs for back porting patches come out with the release of v2.3, this PR is going to add related questions for contributors, which could help everyone know well about the details.

feat: Add backport type in PR template

---

CHANGELOG.md
docs/deploy.md

docs: added back docs for release 2.3

---

web/src/app.tsx
web/src/pages/ServerInfo/List.tsx

resolve #1178 
___
Make the timestamp easy to read.

feat: server info page time stamp display.

---

docs/deploy.md

feat: adjust v2.3

---

web/src/pages/Route/Create.less

#1188
___
- Description
The content of create route display is truncated
- How to fix?
I have updated create.less file  to avoid truncating.

fix: create route display is truncated #1188

---

api/internal/core/store/storehub.go

chore: fix punctuation problem

---

.github/PULL_REQUEST_TEMPLATE

Add test case tips when fixing bugs

docs: Update PULL_REQUEST_TEMPLATE

---

web/src/components/Plugin/PluginPage.tsx

___
- Description
- How to fix?
Delete extra content.

fix: Delete extra content.

---

web/src/pages/Route/List.tsx
web/src/pages/Route/components/DebugViews/DebugDrawView.tsx
web/src/pages/Route/constants.ts
web/src/pages/Route/typing.d.ts

fix:  #1236 
___
- How to fix?
when users want to pass a json params in body, they should use `raw input`  type

fix: remove body type json

---

api/conf/schema.json
api/internal/core/store/validate.go

sync the latest JSON Schema from APISIX
close #1227

chore: sync the latest JSON Schema

---

web/src/global.less

___
- Description
- How to fix?
Change the global.less background-color.

fix: Login page bottom white background.

---

web/src/app.tsx

resolve #1290 
___
- Description
- How to fix?
Delete moment locale.

fix: Switch Language doesn't work.

---

README.md

resolve #1010 
___
- Description
- How to fix?
___
___
___

docs: add demo site's infomation

---

web/src/components/Plugin/PluginDetail.tsx

fix #1260
___
- Description
Document link error for plugins serverless-pre-function and serverless-post-function 
- How to fix?
I have updated PluginDetails.tsx

fix: document link error for plugins serverless-pre-function and serverless-pre-function

---

web/src/pages/Upstream/locales/en-US.ts

feat: i18n

---

README.md

None
Added Good first issue to README

docs: added Good first issue to README

---

api/internal/core/storage/etcd.go
api/internal/core/store/store.go
api/internal/core/store/store_test.go

implement a way to set etcd client

feat: implement a way to set etcd client

---

web/package.json
web/yarn.lock

fix: #1290 
___
- How to fix?
refer to https://github.com/ant-design/ant-design-pro/issues/7940#issuecomment-759273529: upgrade  `@umijs/preset-react` >= 1.7.11
___

fix: upgrade @umijs/preset-react >= 1.7.11

---

CHANGELOG.md
web/cypress/integration/settings/settings-smoketest.spec.js
web/src/pages/Route/components/Step1/MatchingRulesView.tsx

___
- Description
- How to fix?
___
___
___

chore: fix spelling

---

web/cypress/integration/lang/switch-language.spec.js
web/cypress/integration/route/search-route.spec.js

resolve #1290 
___
add switch language test

test: switch language

---

web/src/locales/en-US/component.ts
web/src/locales/zh-CN/component.ts

fix #1343
___
- Description
update description input box
- How to fix?
I have updated the  placeholder in en-US and zh-CN

fix: update description input box

---

web/cypress/integration/route/create-route-with-upstream.spec.js
web/src/pages/Upstream/locales/en-US.ts

resolve #1125  
___
E2E: create Upstream in Route.
1. Create Upstream in Route
2. Select Upstream in Route then Input manually

test: Create Upstream in Route.

---

web/cypress/integration/route/create-route-with-upstream.spec.js

resolve #1317 
___
- Description
- How to fix?
update domSelect and data

fix: CI failed in create-route-with-upstream

---

api/go.mod
api/go.sum

build: upgrade protobuf to v1.3.2

---

web/config/defaultSettings.ts
web/config/proxy.ts
web/cypress/integration/route/online-debug.spec.js
web/cypress/support/commands.js
web/src/components/Plugin/PluginDetail.tsx
web/src/pages/Route/components/DebugViews/DebugDrawView.tsx

fix: #1325 
___
- Description
- How to fix?
update url Regexp to allow `-` in url path, at the same time allow `%` `+` `-` in query params
___
already added.

fix(fe): update url regexp in online debug

---

docs/develop.md

___
- How to fix?
update the doc due to the location of manager-api address configuration changed in #1326

doc:  update location of manager-api address conf to config/defaultSettings.ts

---

NOTICE

___
- Updated the year to 2021

docs: change year to 2021

---

web/src/pages/Route/components/Step1/MatchingRulesView.tsx
web/src/pages/Route/locales/en-US.ts
web/src/pages/Route/locales/zh-CN.ts
web/src/pages/Route/typing.d.ts

resolve #1293 
route vars support IN

feat: route vars support IN

---

.gitignore

___
The `make api-test` in local environment will generate `api/coverage.txt` and download `api/dag-to-lua/` , this PR is going to ignore them in git repo.

chore: git ignore the output of backend unit test

---

api/test/docker/Dockerfile-apisix

#1401
___
- Description
[Failed installing dependency,Could not find header file for OPENSSL](https://github.com/apache/apisix-dashboard/runs/1804604649)
- How to fix?
Dockerfile-apisix adds the specified OpenSSL library address.

fix(be): push pr ci failed

---

api/internal/filter/schema.go

close #1023
___
- Description
Version 2.4 will be released soon，Fix the minor problems left by PR #986
- How to fix?
> [#986 (comment)](https://github.com/apache/apisix-dashboard/pull/986#discussion_r540806679)
This comment modification status code involves many modifications, so don't modify it first.

fix(be): Schema File Minor problems left

---

web/cypress/integration/plugin/create-edit-delete-plugin.spec.js
web/cypress/integration/route/create-route-with-upstream.spec.js
web/cypress/integration/route/online-debug.spec.js
web/src/components/Upstream/UpstreamForm.tsx
web/src/pages/Plugin/List.tsx

#1410 
___
- Description
- How to fix?
1. add success notification after delete plugin successfully
2. check delete successfully to ensure every delete option finished

fix: check delete successfully to ensure every delete option finished

---

web/cypress/fixtures/export-route-dataset.json
web/cypress/fixtures/plugin-list.json
web/cypress/integration/plugin/create-edit-delete-plugin.spec.js
web/cypress/integration/plugin/schema-smocktest.spec.js
web/cypress/integration/route/can-skip-upstream-when-select-service-id.spec.js
web/cypress/integration/route/create-route-with-upstream.spec.js
web/cypress/integration/route/import_export_route.spec.js
web/cypress/integration/route/online-debug.spec.js
web/cypress/integration/service/create-edit-delete-service.spec.js
web/cypress/integration/settings/settings-smoketest.spec.js
web/cypress/support/commands.js
web/scripts/verifyCommit.js
web/src/components/Upstream/UpstreamForm.tsx
web/src/helpers.tsx
web/src/pages/Route/Create.tsx
web/src/pages/Route/components/CreateStep4/CreateStep4.tsx
web/src/pages/Route/components/Step1/MetaView.tsx
web/src/pages/Route/components/Step2/RequestRewriteView.tsx
web/src/pages/Service/Create.tsx

format frontend's codes by using `yarn prettier --write .`

style: format codes

---

api/cmd/managerapi.go
api/test/shell/cli_test.sh

fix #1405 
___
support -v command to show version

feat: support -v command to show version

---

api/internal/handler/tool/tool.go
api/internal/handler/tool/tool_test.go
api/internal/utils/consts/versionMap.go
api/internal/utils/utils.go
api/test/e2e/version_test.go

#1165
Add an API to check the version of manger-api and apisix.

feat: add version match API

---

web/cypress/fixtures/selector.json
web/cypress/integration/consumer/create_and_delete_consumer.spec.js
web/cypress/integration/lang/switch-language.spec.js
web/cypress/integration/metrics/metrics-smoketest.spec.js
web/cypress/integration/plugin/create-edit-delete-plugin.spec.js
web/cypress/integration/route/can-skip-upstream-when-select-service-id.spec.js
web/cypress/integration/route/create-edit-delete-route.spec.js
web/cypress/integration/route/create-route-with-upstream.spec.js
web/cypress/integration/route/import_export_route.spec.js
web/cypress/integration/route/online-debug.spec.js
web/cypress/integration/route/search-route.spec.js
web/cypress/integration/service/create-edit-delete-service.spec.js
web/cypress/integration/settings/settings-smoketest.spec.js
web/cypress/integration/ssl/ssl-smoketest.spec.js
web/cypress/integration/upstream/create_and_delete_upstream.spec.js

resolve #1126 
___
Add Public Selector
___

chore: added global files to contain test selector mappers and public data

---

.github/workflows/deploy-with-docker.yml

___
- Description
- How to fix?
modify config

fix CI failed due to IP restrictions

---

api/conf/schema.json
web/cypress/fixtures/plugin-dataset.json

sync JSON Schema from APISIX version 2.3

chore: sync JSON Schema from APISIX version 2.3

---

web/config/defaultSettings.ts

Fixed sider can provide a better user experience when long content.

feat: fixed sider

---

api/internal/handler/ssl/ssl.go
api/internal/handler/ssl/ssl_test.go

#1161 
#1332
___
- Description
Refactor SSL unit testing to remove etcd dependency

feat: refactor ssl unit test

---

CHANGELOG.md

fix: fix typo of CHANGELOG.md

---

web/src/pages/Consumer/List.tsx
web/src/pages/Consumer/locales/en-US.ts
web/src/pages/Consumer/locales/zh-CN.ts
web/src/pages/Plugin/List.tsx
web/src/pages/Plugin/locales/en-US.ts
web/src/pages/Plugin/locales/zh-CN.ts
web/src/pages/Route/List.tsx
web/src/pages/Route/locales/en-US.ts
web/src/pages/Route/locales/zh-CN.ts
web/src/pages/SSL/List.tsx
web/src/pages/SSL/locales/en-US.ts
web/src/pages/SSL/locales/zh-CN.ts
web/src/pages/Service/List.tsx
web/src/pages/Service/locales/en-US.ts
web/src/pages/Service/locales/zh-CN.ts

https://github.com/apache/apisix-dashboard/issues/1458
___
- Description
consistent name for list page

chore: consistent name for list page

---

web/cypress/integration/route/search-route.spec.js

___
In the for loop of the `search-route` test, add `timeout` for the click

test: improve the stability of frontend  e2e

---

Makefile
README.md

docs: update Release info & Makefile tip

---

web/src/components/Plugin/PluginPage.tsx
web/src/components/Plugin/locales/en-US.ts
web/src/components/Plugin/locales/zh-CN.ts
web/src/locales/zh-CN.ts

added tip for Plugin module, to let users know how to update schema.json after modifying plugins.
NOTE: this is only a tip, no need to add a testcase.

feat: added tip for Plugin module

---

web/src/pages/User/components/LoginMethodPassword.tsx
web/src/pages/User/locales/en-US.ts
web/src/pages/User/locales/zh-CN.ts

add tips on login page

---

web/src/pages/Route/typing.d.ts

Remove duplicate code 

---

docs/deploy-with-rpm.md

fix: modify the rpm link for 2.4

---

api/test/e2enew/version/version_suite_test.go
api/test/e2enew/version/version_test.go

#1500
___
-  Rewrite e2e test(version_test) with ginkgo

feat: rewrite e2e test(version_test) with ginkgo

---

.github/workflows/backend-e2e-test.yml
.github/workflows/frontend-e2e-test.yml
api/conf/conf.yaml
api/conf/schema.json
api/internal/conf/conf.go
api/internal/handler/plugin/plugin.go
api/internal/handler/plugin/plugin_test.go

close #1508
___
1. All plugins are included in schema.json
2. Add a new configuration item plugins in conf.yaml to control which plugins are displayed in the dashboard.

feat: support configure enabled plugin list & sync JSON Schema

---

web/cypress/fixtures/plugin-dataset.json

feat(FE): add dubbo test

---

api/conf/conf.yaml
api/test/docker/manager-api-conf.yaml

___
- Description
- How to fix?
___
___
___

chore: remove whitespace before commas

---

api/test/e2enew/route_online_debug/route_online_debug_test.go

#1521
___
- Description
debug_ online_ route_ The test case of test E2E is unstable, which is easy to cause irregular CI failure.
- How to fix?
sleep for data sync

fix(be): fix ci failed

---

docs/en/latest/FAQ.md
docs/en/latest/I18N_USER_GUIDE.md
docs/en/latest/IMPORT_OPENAPI_USER_GUIDE.md
docs/en/latest/USER_GUIDE.md
docs/en/latest/api/api.md
docs/en/latest/back-end-e2e.md
docs/en/latest/config.json
docs/en/latest/deploy-with-docker.md
docs/en/latest/deploy-with-rpm.md
docs/en/latest/deploy.md
docs/en/latest/develop.md
docs/en/latest/front-end-e2e.md

docs: refactor contents

---

docs/en/latest/FAQ.md
docs/en/latest/back-end-e2e.md

docs: fix broken links

---

web/src/components/Plugin/PluginDetail.tsx

- Related issues #1528
___
- Description
- How to fix?
Change the link to https://apisix.apache.org/docs/apisix/plugins/${name} and https://apisix.apache.org/docs/apisix/plugins/serverless

fix: fix broken links

---

docs/en/latest/config.json

docs: fix invalid config
related PR https://github.com/apache/apisix-website/pull/221

docs: fix invalid config

---

README.md

___
- Description
- How to fix?
___
___
___

docs: updated broken docs url

---

docs/deploy-with-rpm.md

___
- Description
origin reported link: https://github.com/apache/apisix-dashboard/pull/1497#issuecomment-783783397
- How to fix?
___
update error rpm link in branch v2.4
master
commit: f574fcd07e2d53f088766cb3a7ab1ede37e527b5
v2.4

Backport: Update v2.4 rpm link in branch v2.4

---

docs/en/latest/config.json

Update Sidebar Configuration, so we will have a sidebar here[1].
[1] https://apisix.apache.org/docs/dashboard/FAQ/

fix: update sidebar config

---

web/src/components/Plugin/PluginPage.tsx

- Related issues #1543
___
- Description
- How to fix?
Fix #1543 broken link.

fix: fix faq broken link

---

api/test/e2enew/base/base.go
api/test/e2enew/ssl/ssl_suite_test.go
api/test/e2enew/ssl/ssl_test.go

Because some function in SSL e2e test is not covered.
This PR is to cover those functions.

chore: improve ssl e2e test coverage

---

api/test/e2enew/plugin_config/plugin_config_test.go

___
chore: cover the plugin config create function.

chore: cover plugin config create function

---

api/test/e2enew/healthz/healthz_suite_test.go
api/test/e2enew/healthz/healthz_test.go

Add health e2e test that we don't have before.

chore: add health e2e test

---

api/test/e2enew/plugin/plugin_suite_test.go
api/test/e2enew/plugin/plugin_test.go

___
Add plugin e2e test that we don't have before.

chore: add plugin test

---

web/src/pages/Upstream/locales/en-US.ts
web/src/pages/Upstream/locales/zh-CN.ts

related PR： https://github.com/apache/apisix/pull/3815
added description for the Upstream module.

chore: added description for Upstream module

---

web/src/components/Plugin/PluginPage.tsx
web/src/components/RightContent/index.tsx
web/src/pages/User/components/LoginMethodPassword.tsx

___
Adjust the **How to update username/password?** link open in a new tab.
Change the documentation link to the official website.
Use the `a` tag to replace the `onClick` event.

feat: change the doc link to website

---

web/cypress/integration/route/import_export_route.spec.js
web/cypress/integration/route/online-debug.spec.js

fix: fe e2e error  for pr 1538

---

.github/workflows/frontend-e2e-test.yml
web/cypress.json

___
Currently front-end e2e is running very unstable on GitHub action, add upload files to github and download them for developers to locate the problem
The output file is here:

feat: add upload test result

---

.github/ISSUE_TEMPLATE/bug-report.md

Fix #944
If this issue template can be accepted, I will create another PR to standardize all of APISIX's repo issue templates.
___

chore: improve bug report template

---

api/internal/route.go

Fix #1609
___
Remove unnecessary session and cookie.

feat: remove unnecessary cookie session

---

.actions/ASF-Release.cfg
netlify.toml
web/package.json
web/yarn.lock

___
- Description
- How to fix?
___
___
___

feat: update yarn.lock

---

README.md
web/src/pages/User/Login.less
web/src/pages/User/Login.tsx

___
- Description
login module fixes
- size of logo
- removed settings from login page
___
___
___
issue
- #1626

fix: login_module_#1626

---

api/internal/handler/authentication/authentication.go
api/internal/handler/consumer/consumer.go
api/internal/handler/data_loader/route_export.go
api/internal/handler/data_loader/route_import.go
api/internal/handler/route/route.go
api/internal/handler/ssl/ssl.go
api/internal/utils/consts/error.go

fix #758 
Move the error msg to error.go.So that we can update the error msg more easily.
___

chore: generalize error msg to error.go

---

.github/PULL_REQUEST_TEMPLATE

chore: update PULL_REQUEST_TEMPLATE

---

api/test/docker-deploy/docker-compose.yaml
api/test/docker/docker-compose.yaml
web/src/pages/User/Login.less
web/src/pages/User/Login.tsx

Github hyperlink(icon) added has been added to header section of login page
User will be directed to https://apisix.apache.org.
Github hyperlink(icon) has been added to header section of login page
User will be directed to https://apisix.apache.org.
fix/resolve #1632 
**Checklist:**
screenshot of changes done 
@LiteSun @juzhiyuan

feat: added github link to header #1632

---

docs/en/latest/config.json

add CHANGELOG.md to sidebar
**Checklist:**

docs: add CHANGELOG.md to sidebar

---

README.md

docs: update readme for new release 2.5

---

.github/semantic.yml

https://github.com/apache/apisix-dashboard/issues/1397
semantic-pull-requests app:   https://github.com/apps/semantic-pull-requests

feat: added policy for semantic-pr

---

api/test/e2e/base.go

Hi, I found that there are some debug lines in `api/test/e2e/base.go`.
These lines are local only. The developer can get the error info from the terminal. But I think there is no need to keep these lines in the project.
This PR is for removing them.
Remove the debug lines.
**Checklist:**

chore: remove debug line

---

web/src/components/RightContent/index.tsx

ref: [comment](https://github.com/apache/apisix-dashboard/issues/1717#issuecomment-815795440)
resolve #1717
**Checklist:**

fix: 401 for version_match without Authrorization token

---

web/cypress.json
web/cypress/integration/pluginTemplate/create-plugin-template-with-route.spec.js
web/cypress/integration/route/create-edit-duplicate-delete-route.spec.js
web/cypress/integration/route/create-route-with-proxy-rewrite-plugin.spec.js
web/cypress/integration/route/search-route.spec.js
web/cypress/support/commands.js

fix: FE CI unstable

---

api/internal/core/store/store.go
api/internal/handler/label/label.go
api/test/e2e/label_test.go

fix: null value instead of empty slice during JSON marshalling for GET labels

---

web/package.json
web/src/components/PanelSection/index.tsx
web/src/components/Plugin/PluginPage.tsx
web/src/components/Plugin/data.tsx
web/src/components/Plugin/locales/en-US.ts
web/src/components/Plugin/locales/zh-CN.ts
web/src/components/RightContent/AvatarDropdown.tsx
web/src/components/Upstream/UpstreamForm.tsx
web/src/components/Upstream/components/TLS.tsx
web/src/components/Upstream/components/passive-check/Type.tsx
web/src/components/Upstream/locales/en-US.ts
web/src/components/Upstream/locales/zh-CN.ts
web/src/global.less
web/src/helpers.tsx
web/src/pages/Route/components/DebugViews/DebugDrawView.tsx
web/src/pages/Route/components/Step1/MatchingRulesView.tsx
web/src/pages/Route/components/Step1/MetaView.tsx
web/src/pages/Route/components/Step1/ProxyRewrite.tsx
web/src/pages/Route/components/Step1/RequestConfigView.tsx
web/src/pages/Route/locales/en-US.ts
web/src/pages/Route/locales/zh-CN.ts
web/src/pages/Route/transform.ts
web/src/pages/Route/typing.d.ts
web/src/pages/Upstream/Create.tsx
web/src/pages/Upstream/locales/en-US.ts
web/src/pages/Upstream/locales/zh-CN.ts
web/src/typings.d.ts
web/yarn.lock

related issue: #1775 
**Checklist:**

chore: keep using English as comments & update plugin type

---

api/internal/handler/route_online_debug/route_online_debug.go
api/internal/handler/route_online_debug/route_online_debug_test.go
web/src/components/RawDataEditor/RawDataEditor.tsx
web/src/locales/en-US/component.ts
web/src/locales/zh-CN/component.ts
web/src/pages/Route/components/DebugViews/DebugDrawView.tsx
web/src/pages/Route/constants.ts
web/src/pages/Route/typing.d.ts

1. Support gzip content encoding.
2. Highlight response body.
3. Allow to copy response body.
4. Display response code.
5. Adjust the style of the display response header.
**Checklist:**

feat: Improve debug view

---

web/config/defaultSettings.ts

Dark them for menu given by default
menu sidebar changed to darkmode
fix/resolve #1810 
**Checklist:**

style: default dark sidebar added

---

api/internal/core/entity/format.go
api/internal/core/entity/format_test.go
web/cypress/fixtures/data.json
web/cypress/fixtures/selector.json
web/cypress/integration/upstream/create_and_edit_upstream_with_no_nodes.spec.js
web/src/components/Upstream/components/Nodes.tsx
web/src/components/Upstream/service.ts
web/src/pages/Route/typing.d.ts
web/src/pages/Upstream/locales/en-US.ts
web/src/pages/Upstream/typing.d.ts

During rechecking #1803 , there is a problem occured when I try to configure a upstream with no nodes.
Test steps:
1. Create an upstream with no nodes
2. Configure this upstream with no changes, an Submit the data, the error occured
This pr tried to change the fe logic to solve this problem.
Doc: 
Delete `k8s_deployment_info` in upstream just refer to https://github.com/apache/apisix/blob/359e0906c5a3f0149c0f6a44aff927d4c4eb8c6b/CHANGELOG.md#220
TODO
None
**Checklist:**

fix: can not configure upstream with no nodes

---

web/src/components/Upstream/locales/zh-CN.ts

Fix Chinese typos in the `retries.tooltip` field of upstream component
修正中文本地化错别字 in the `retries.tooltip` field of upstream component
APISIX Dashboard `/upstream/create`
`表是` -> `表示`
**Checklist:**

docs: fix Chinese typos in the `retries.tooltip` field of upstream component

---

web/cypress/integration/route/create-route-with-proxy-rewrite-plugin.spec.js

chore: refactored test create-route-with-proxy-rewrite-plugin.spec.js

---

web/cypress/integration/route/create-route-when-not-select-upsteam-id.spec.js

chore: refactored test create-route-when-not-select-upstream-id.spec.js

---

web/src/components/Plugin/locales/en-US.ts

I found this name is "可观测" in chinese. So I think `Observability` is better than "Tracing & Metrics & Logging". 
**Checklist:**

chore: update plugin catagory display name.

---

web/cypress/integration/route/online-debug.spec.js

chore: refactored test online-debug.spec.js

---

web/cypress/integration/upstream/create_and_delete_upstream.spec.js

chore: refactored test create_and_delete_upstream.spec.js

---

web/cypress/integration/ssl/ssl-smoketest.spec.js

chore: refactored test ssl-smoketest.spec.js

---

web/cypress/integration/settings/settings-smoketest.spec.js

chore: refactored test settings-smoketest.spec.js

---

web/cypress/integration/service/edit-service-with-upstream.spec.js

chore: refactored test edit-service-with-upstream.sepc.js

---

web/cypress/integration/route/search-route.spec.js

chore: refactored test search-route.spec.js

---

web/cypress/integration/route/import_export_route.spec.js

chore: refactored test import_export_route.spec.js

---

web/cypress/integration/route/create-route-with-limit-count-plugin-form.spec.js

chore: refactored test create-route-with-limit-count-plugin-form.spec.js

---

web/cypress/integration/route/create-route-with-api-breaker-form.spec.js

chore: refactored test create-route-with-api-breaker-from.spec.js

---

web/cypress/integration/rawDataEditor/test-rawDataEditor.spec.js

chore: refactored test-rawDataEditor.spec.js

---

web/cypress/integration/pluginTemplate/create-plugin-template-with-route.spec.js

chore: refactored test create-plugin-template-with-route.spec.js

---

web/cypress/integration/route/create-edit-duplicate-delete-route.spec.js

chore: refactor test create-edit-duplicate-delete-route.spec.js

---

web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js

chore: refactored test create-delete-in-drawer-plugin

---

web/cypress/integration/consumer/create-with-referer-restriction-form.spec.js

chore: refactored test create-with-referer-restriction-form

---

web/cypress/integration/consumer/create-upstream-with-limit-req-form.spec.js

chore: refactored test create-upstream-with-limit-request-form

---

web/cypress/integration/service/save-paginator-status.spec.js

chore: refactored test save-paginator-status.spec.js

---

web/cypress/integration/route/create-route-with-limit-req-form.spec.js

chore: refactored test create-route-with-limit-req-form.spec.js

---

web/cypress/integration/consumer/create-with-limit-conn-form.spec.js

chore: refactored test create-with-limit-conn-form

---

web/cypress/integration/consumer/create-consumer-with-proxy-mirror-form.spec.js

chore: refactored test create-consumer-with-proxy-mirror-form

---

web/cypress/integration/consumer/create-consumer-with-limit-count-plugin-form.spec.js

chore: refactored test create-consumer-with-limit-count

---

web/cypress/integration/consumer/create-consumer-with-api-breaker-plugin-form.spec.js

chore: refactored test create-consumer-with-api-breaker

---

docs/en/latest/FAQ.md

How to allow all IPs to access APISIX Dashboard is a common user question, and we should record it in the FAQ.
This PR is to record in the FAQ document how to allow all IPs to access APISIX Dashboard.
**Checklist:**

docs: FAQ Add a guide to allow all IP access

---

docs/en/latest/deploy-with-rpm.md

Add visit the dashboard page description.
fix/resolve #1368
**Checklist:**

docs: add the visit the dashboard

---

CHANGELOG.md

cherry pick CHANGELOG for version 2.6.1  from branch `release/2.6.1`

docs: cherry pick CHANGELOG for version 2.6.1

---

web/cypress/integration/route/search-route.spec.js
web/src/pages/Route/List.tsx

added route `path` search option in route page
fix/resolve #1916 
**Checklist:**

feat: added route path search

---

web/cypress/integration/route/search-route.spec.js

cy.reload() were optimised so that test can be more efficient and fast.
test running time decreased by 27+ seconds @liuxiran 
fix/resolve #1925 
**Checklist:**

fix: route search test optimised

---

README.md

add cypress badge in README.md
**Checklist:**

docs: add cypress badge

---

docs/en/latest/FAQ.md

fix/resolve #1948 
**Checklist:**

docs: fixed counting for FAQ

---

api/internal/handler/tool/tool.go
api/internal/handler/tool/tool_test.go
api/test/e2enew/version/version_test.go

provide more information in the prompt message when dashboard version and APISIX don't match
resolve #1944 
**Checklist:**

feat: When Dashboard and APISIX version do not match, make the prompt information clearer (#1944)

---

docs/en/latest/deploy-with-rpm.md

Update the dashboard installation version for installing from rpm.
fix/resolve
**Checklist:**

docs: update the dashboard installation version

---

api/internal/filter/authentication.go

Add more detailed log messages to authentication.go with new log messages.
This PR will add more detailed log messages to authentication.go with new log messages.
Fixes #1964 
**Checklist:**

feat: add more detailed log messages to authentication.go

---

web/cypress/integration/consumer/create-consumer-with-limit-count-plugin-form.spec.js
web/cypress/integration/route/create-route-with-limit-count-plugin-form.spec.js
web/src/components/Plugin/UI/limit-count.tsx
web/src/components/Plugin/locales/en-US.ts

add validate trigger and correct tip message for limit-count
fix/resolve
**Checklist:**

chore: add validate trigger and correct tip message for limit-count plugin

---

README.md

Remove the Experimental flag due to we are going to release 2.7.x
None
**Checklist:**

docs: update README without flag

---

CHANGELOG.md

Fix title's style of version 1.0.0 in CHANGELOG.md, it looks smaller than other versions...

docs: fix title's style in CHANGELOG.md

---

web/src/components/Upstream/components/Nodes.tsx
web/src/components/Upstream/components/active-check/Healthy/HttpStatuses.tsx
web/src/components/Upstream/components/active-check/Unhealthy/HttpStatuses.tsx
web/src/components/Upstream/constant.ts

improve grid layout for Upstream components when screen  width between 992px and 1600px.
resolve #2016
**Checklist:**

perf(Upstream): improve grid layout for Upstream components when screen  width between 992px and 1600px

---

api/test/docker/setup.sh

Removed the part of the script responsible for downloading the apisix dockerfile.
Combined with #1744 
**Checklist:**

chore: update setup script

---

api/test/e2enew/migrate/migrate_suite_test.go
api/test/e2enew/upstream/upstream_test.go

fix backend e2e test case unstable
**Checklist:**

fix: backend e2e test case unstable

---

api/test/shell/cli_test.sh
docs/en/latest/IMPORT_OPENAPI_USER_GUIDE.md

docs: fix spelling

---

api/internal/core/migrate/dataset.go
api/test/e2enew/migrate/migrate_test.go

fix/resolve:
correct spelling
**Checklist:**

chore: correct spelling

---

web/src/pages/Route/transform.ts

fix/resolve: 
remove redundant code
**Checklist:**

chore: remove redundant code

---

docs/en/latest/deploy-with-rpm.md

the link for 2.8 rpm is wrong in our doc: https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy-with-rpm.md
update to the latest one
fix/resolve https://github.com/apache/apisix-dashboard/issues/2134
**Checklist:**

docs: update rpm link in deploy-with-rpm.md

---

api/test/e2enew/route/route_with_plugin_uri_blocker_test.go

Add create route test case, with uri blocker plugin.
**Checklist:**

test: add update route with plugin uri blocker case

---

web/src/components/Upstream/components/Nodes.tsx

resolve the issue of #2181 ，modified the style of the input

fix: route editing form format error

---

.gitignore
Makefile

Convert coverage.txt to coverage.html after test for readability.
**Checklist:**

test: convert coverage.txt to coverage.html for readability.

---

README.md

fix source codes link from https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md  to https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/install.md
**Checklist:**

fix: build then launch link

---

api/test/e2enew/migrate/migrate_test.go

When we submit a PR, sometimes the migrate case will have an ensuing error. It will be fixed in this PR.
fix #2227
**Checklist:**

fix: migrate testcase CI crash

---

api/test/docker/docker-compose.yaml
api/test/docker/upstream.conf
api/test/e2enew/base/base.go
api/test/e2enew/stream_route/stream_route_suite_test.go
api/test/e2enew/stream_route/stream_route_test.go

Fix frequent failures in StreamRoute E2E tests.
**Checklist:**

fix: stream route testcase CI failed frequent

---

.github/workflows/auto-build-rpm.yml

The latest branch of apisix-build-tools introduces some updates to the dashboard, so we need to use its master branch for the build.
**Checklist:**

feat: use apisix-build-tools master branch

---

docs/en/latest/install.md

Fix the download link in install.md.
fix/resolve #2256 
**Checklist:**

fix(docs): download link of install.md

---

api/test/e2enew/auth/auth_suite_test.go
api/test/e2enew/auth/authentication_test.go

Move backend e2e to ginkgo implement.
part of #2197 
**Checklist:**

test: migrate auth e2e to ginkgo implement

---

.gitignore
api/test/docker/setup.sh

This script was created to aid the developers with the environment and config required for testing e2e tests on ginkgo suite locally. This script was not maintained for a long time. So it is updated accordingly and made it work again.
**Checklist:**

chore: update setup script for e2e tests (ginkgo)

---

docs/en/latest/install.md

fix the command error
**Checklist:**

docs: fix command error.

---

web/cypress/integration/upstream/create_and_edit_upstream_with_custom_chash_key.spec.js
web/src/pages/Upstream/List.tsx
web/src/pages/Upstream/locales/en-US.ts
web/src/pages/Upstream/locales/zh-CN.ts

Add upstream id in form.
fix #2319 
**Checklist:**

feat: add upstream id in form

---

web/src/hooks/usePagination.ts
web/src/pages/Consumer/List.tsx
web/src/pages/Plugin/List.tsx
web/src/pages/PluginTemplate/List.tsx
web/src/pages/Route/List.tsx
web/src/pages/SSL/List.tsx
web/src/pages/Service/List.tsx
web/src/pages/Upstream/List.tsx

Extract paging related functions into standalone hook
resolve #1621
**Checklist:**

chore: Extract paging related functions into standalone hook

---

web/cypress/integration/consumer/create_and_delete_consumer.spec.js
web/src/locales/en-US/component.ts
web/src/locales/zh-CN/component.ts
web/src/pages/Consumer/Create.tsx
web/src/pages/Consumer/List.tsx
web/src/pages/Consumer/components/Step1.tsx
web/src/pages/Route/List.tsx

resolve #1630
1.Create page, add description under name input box 
2.Create/Edit/Delete Success prompt to delete spaces 
3.List page, add enabled plugin fields
**Checklist:**

feat: improve Consumer module

---

CHANGELOG.md

Fix the formatting error of CHANGELOG.md; For release/2.11
**Checklist:**

fix: format error in changelog

---

docs/en/latest/develop.md

This link is invalid, we should fix it.
**Checklist:**

docs: fix invalid link

---

README.md

update online playground url
**Checklist:**

docs: update online playground url

---

web/src/components/Footer/index.tsx
web/src/components/PluginFlow/locales/en-US.ts
web/src/components/Upstream/locales/en-US.ts

Update the year of copyright and fix typo.
**Checklist:**

chore: update the year of copyright and fix typo

---

docs/en/latest/install.md

fix/resolve #2426
1.Remove hyperlinks from documents
**Checklist:**

docs: Remove hyperlinks from documents

---

docs/en/latest/install.md

Update RPM install package link. 
**Checklist:**

docs: Update RPM install  package link

---

.asf.yaml

Reduce the minimum number of reviewers to increase review speed.

chore: reduce minimal reviewer to 2

---

docs/en/latest/config.json

Add the documents imported by DataLoader and OpenAPI3 to the sidebar.

docs: add new import and export docs to sidebar

---

web/src/pages/Route/locales/tr-TR.ts

Translating Turkish for new features
https://github.com/apache/apisix-dashboard/pull/2480#discussion_r907273383

Translating Turkish for new features

---

.github/workflows/license-checker.yml
.licenserc.yaml
api/internal/conf/conf_test.go
web/.editorconfig
web/.eslintignore
web/.prettierignore

Add skywalking eye as a license checker.
**Checklist:**

feat: add skywalking-eye license checker

---

.github/workflows/auto-build-rpm.yml
.github/workflows/backend-cli-test.yml
.github/workflows/backend-e2e-test.yml
.github/workflows/backend-unit-test.yml
.github/workflows/codeql-analysis.yml
.github/workflows/deploy-with-docker.yml
.github/workflows/frontend-e2e-test.yml
.github/workflows/frontend-plugin-e2e-test.yml
.github/workflows/gitleaks.yml
.github/workflows/go-lint.yml
.github/workflows/license-checker.yml
.github/workflows/make-build.yaml
.github/workflows/release-test.yml
.github/workflows/test-frontend-multiple-node-build.yml
api/go.mod

Make all required CIs run on the `next` branch.

chore: add ci to next branch

---

api/cmd/root.go
api/main.go

Improvements to the CLI and Configuration Management modules to support the following capabilities:
- Rewrite configuration items via CLI
- Rewrite configuration items via ENV
- Remove the `working directory` concept: We will migrate to Go 1.16+ to use the go embed capability to embed frontend resources into the binary to reduce build toolchain complexity and deployment difficulty.
- Modify configuration modules to reduce coupling
**Checklist:**

chore: simplify CLI entry

---

.github/workflows/backend-cli-test.yml
.github/workflows/backend-e2e-test.yml
.github/workflows/backend-unit-test.yml
.github/workflows/frontend-e2e-test.yml
.github/workflows/frontend-plugin-e2e-test.yml

Pause the test CI on the next branch to add new content.

chore: pause test in next branch

---

.github/workflows/backend-cli-test.yml
.github/workflows/backend-e2e-test.yml
.github/workflows/backend-unit-test.yml
.github/workflows/frontend-e2e-test.yml
.github/workflows/frontend-plugin-e2e-test.yml

Reverts apache/apisix-dashboard#2543

chore: resume test in next branch

---

api/internal/core/store/store_test.go

Fix crash bug in `store` unit test

test: fix store unit cases

---

api/config/config.yaml
api/internal/config/config.go
api/internal/config/structs.go

Add the feature gate configuration item. 
It will be like the same concept in K8s, allowing us to control whether a feature is enabled or not through a profile. 
The current expected usage scenario, access control Demo (it has potential security risks and is only used as a sample for developers), we control it to be turned on through a configuration file instead of turning it on by default and avoiding the security risk.

feat: add feature gate

---

web/src/app.tsx
web/src/typings.d.ts

Compatible with new request formats on the back end.

fix: update request interceptor

---

api/internal/handler/resources/resources.go

Improve the resource controller code to make it common sense and improve readability.

feat: improve resource handler (part 1)

---

.github/workflows/release-test.yml
api/internal/handler/authentication/authentication.go
api/internal/handler/handler.go

Modify the authentication controller input annotation so that it reads the JSON request body properly.

fix: authentication handler input annotation

---

web/cypress/support/commands.js

Fix the success judgment condition of the Cypress login command.

fix: Cypress login command

---

web/src/pages/Route/constants.ts
web/src/typings.d.ts

Support HTTP method `PURGE` for clean cache.
**Checklist:**

feat: support purge method

---

web/src/components/Upstream/components/Scheme.tsx
web/src/components/Upstream/locales/en-US.ts
web/src/components/Upstream/locales/tr-TR.ts
web/src/components/Upstream/locales/zh-CN.ts

Add protocol support for L4 and pubsub to Upstream.
**Checklist:**

feat: support more upstream scheme

---

CHANGELOG.md
README.md

Add CHANGELOG modification of `2.13.1`.
fix #2653 
**Checklist:**

feat: release 2.13.1 for master

---

api/test/docker/docker-compose.yaml
api/test/e2e/base/base.go
api/test/e2e/upstream/upstream_test.go

The use case in E2E relies on external services and network fluctuations will cause the test to fail, so this PR replaces it with an internal httpbin service.
**Checklist:**

fix: remove cases external service dependency

---

NOTICE

- the year was wrongly mentioned 
the year was wrongly mentioned in the notice
fix #2724 
**Checklist:**

chore: update the year in the  NOTICE

---

web/cypress/e2e/plugin/plugin-schema.cy.js
web/src/components/Plugin/PluginDetail.tsx

Backport https://github.com/apache/apisix-dashboard/pull/2718 to release/2.15

fix: plugin configuration lost in editor (#2718)

---

web/cypress/e2e/route/create-route-with-proxy-rewrite-plugin.cy.js
web/src/pages/Route/components/Step1/ProxyRewrite.tsx

fix/resolve #2381 
**Checklist:**

fix: change regex template to optional in proxy write

---

web/src/helpers.tsx
web/src/pages/SSL/typing.d.ts

fix/resolve #2476 
**Checklist:**

fix: ssl table expiration time display

---

api/internal/core/entity/entity.go
api/test/e2e/route/route_test.go
web/cypress/e2e/route/create-route-with-proxy-rewrite-plugin.cy.js
web/src/helpers.tsx
web/src/pages/Route/components/Step1/ProxyRewrite.tsx
web/src/pages/SSL/typing.d.ts

chore: backport commits to 2.15

---

web/cypress/e2e/plugin/create-delete-in-drawer-plugin.cy.js
web/src/pages/Plugin/List.tsx

fix/resolve #2740 
**Checklist:**

fix: disable global plugin invalid

---

api/internal/core/entity/format.go
api/internal/core/entity/format_test.go
web/cypress/e2e/route/create-edit-duplicate-delete-route.cy.js
web/src/components/Upstream/components/Nodes.tsx
web/src/components/Upstream/service.ts

fix/resolve #2449 
**Checklist:**

feat: support ipv6 in upstream nodes

---

api/internal/core/entity/format.go
api/internal/core/entity/format_test.go

fix/resolve #2661 
**Checklist:**

fix: upstream nodes metadata miss

---

web/cypress/e2e/consumer/create_and_delete_consumer.cy.js
web/src/pages/Consumer/Create.tsx
web/src/pages/Consumer/typing.d.ts

Refer to a slack user report https://the-asf.slack.com/archives/CUC5MN17A/p1684470370003649
**Checklist:**

fix: edit comsumer without plugin

---

docs/en/latest/install.md

The instlal md is missing the default configuration file, and the '-v' parameter must be used with an absolute path.

docs: update install md

---

api/internal/core/store/store.go

fix/resolve #2919
**Checklist:**
- [x ] Did you explain what problem does this PR solve? Or what new features have been added?

fix: etcd watch失败时，内存泄漏 #2919

---

src/apis/protos.ts
src/locales/en/common.json
src/routes/protos/add.tsx
src/routes/protos/detail.$id.tsx
src/routes/protos/index.tsx
src/utils/form-producer.ts
src/utils/producer.ts

feat: protos edit

---

.github/workflows/codeql-analysis.yml
src/routes/global_rules/add.tsx
src/routes/global_rules/detail.$id.tsx
src/routes/protos/add.tsx
src/routes/protos/detail.$id.tsx

chore: clear useless things

---

.asf.yaml

Fix according to the records here: https://github.com/apache/infrastructure-asfyaml/commit/6a03ced07e97f45656d21348e42d11fd60686b52
Because I received the following email:
```
An error occurred while processing the github feature in .asf.yaml:
while parsing a mapping
in "apisix-dashboard.git/.asf.yaml::github", line 20, column 1:
^ (line: 20)
unexpected key not in schema 'notifications'
in "apisix-dashboard.git/.asf.yaml::github", line 24, column 1:
pullrequests: notifications@ap ...
^ (line: 24)
---
With regards, ASF Infra.
For further information, please see the .asf.yaml documentation at: …
```

fix: `.asf.yaml` format

---

src/components/form-slice/FormItemPlugins/PluginCardList.tsx
src/components/form-slice/FormItemPlugins/PluginEditorDrawer.tsx
src/components/form-slice/FormItemPlugins/SelectPluginsDrawer.tsx
src/components/form-slice/FormItemPlugins/index.tsx
src/components/form-slice/FormPartUpstream/FormItemNodes.tsx
src/components/page-slice/plugin_metadata/PluginMetadata.tsx

fix: remove redudent observers

---

e2e/tests/auth.spec.ts
e2e/tsconfig.json
e2e/utils/req.ts
e2e/utils/test.ts
eslint.config.ts
playwright.config.ts
tsconfig.json

According to changes in #3056 and locally, some adjustments were found to be missing or inappropriate in the previous `tsconfig` and `eslint` configuration. 
So I made some adjustments according to the actual situation.
Mainly includes:
1. Correcting the location of tsconfig to ensure that dashboard is built correctly
2. Adjust the eslint configuration to ensure that the rules in e2e files and src files are as consistent as possible.

fix: e2e related tsconfig and eslint config

---

src/components/form-slice/FormSection/index.tsx

Previously, the TOC box wouldn't react when form items appeared or disappeared in the form items section, but it works correctly after the fix.

fix: toc box rendering when form items changed

---

.github/workflows/e2e.yml
e2e/server/docker-compose.common.yml

* run e2e test at 2 AM every day
* use dev image as dev and e2e server image

feat(workflows/e2e): run at 2AM every day, use dev image

---

.github/workflows/e2e.yml

Testing workflow cannot be triggered normally due to lack of conditions.

fix(workflow): scheduled test

---

src/apis/stream_routes.ts

support delete all stream routes

feat: support delete all stream routes

---

e2e/tests/routes.clear-upstream-field.spec.ts
e2e/utils/ui/routes.ts
src/components/form-slice/FormPartRoute/util.ts
src/routes/routes/add.tsx
src/routes/routes/detail.$id.tsx
src/routes/stream_routes/add.tsx
src/routes/stream_routes/detail.$id.tsx
src/utils/form-producer.ts

fix(routes, stream_routes): clear upstream when has upstream_id

---

e2e/server/nginx.conf
package.json
pnpm-lock.yaml
vite.config.ts

This reverts commit 1bdbfa66852b3b843f3b1c91e78aee9154c071cf.
There have been many changes to APISIX recently, and a new version needs to be released.
But I don't have time to adapt the corresponding gzip configuration on apisix, so I can only revert this commit for now.
fix/resolve #
**Checklist:**

Revert "feat: generate gzip assets during build (#3178)"
